// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package filesystem

import (
	"fmt"
	"path/filepath"
	"strings"

	"android/soong/android"
	"android/soong/response"
)

type fsverityProperties struct {
	// Patterns of files for fsverity metadata generation.  For each matched file, a .fsv_meta file
	// will be generated and included to the filesystem image.
	// etc/security/fsverity/BuildManifest.apk will also be generated which contains information
	// about generated .fsv_meta files.
	Inputs []string
}

func (f *filesystem) writeManifestGeneratorRspFile(ctx android.ModuleContext, rspPath android.OutputPath, matchedSpecs []android.PackagingSpec, rebasedDir android.OutputPath) {
	var buf strings.Builder
	var inputs []string
	for _, spec := range matchedSpecs {
		inputs = append(inputs, rebasedDir.Join(ctx, spec.RelPathInPackage()).String())
	}
	err := response.WriteRspFile(&buf, inputs)
	if err != nil {
		// There should never be I/O errors writing to a bytes.Buffer.
		panic(err)
	}
	android.WriteFileRule(ctx, rspPath, buf.String())
}

func (f *filesystem) buildFsverityMetadataFiles(ctx android.ModuleContext, builder *android.RuleBuilder, specs map[string]android.PackagingSpec, rootDir android.OutputPath, rebasedDir android.OutputPath) {
	match := func(path string) bool {
		for _, pattern := range f.properties.Fsverity.Inputs {
			if matched, err := filepath.Match(pattern, path); matched {
				return true
			} else if err != nil {
				ctx.PropertyErrorf("fsverity.inputs", "bad pattern %q", pattern)
				return false
			}
		}
		return false
	}

	var matchedSpecs []android.PackagingSpec
	for _, relPath := range android.SortedKeys(specs) {
		if match(relPath) {
			matchedSpecs = append(matchedSpecs, specs[relPath])
		}
	}

	if len(matchedSpecs) == 0 {
		return
	}

	fsverityBuilderPath := android.PathForModuleOut(ctx, "fsverity_builder.sh")
	metadataGeneratorPath := ctx.Config().HostToolPath(ctx, "fsverity_metadata_generator")
	fsverityPath := ctx.Config().HostToolPath(ctx, "fsverity")

	cmd := builder.Command().Tool(fsverityBuilderPath)

	// STEP 1: generate .fsv_meta
	var sb strings.Builder
	sb.WriteString("set -e\n")
	cmd.Implicit(metadataGeneratorPath).Implicit(fsverityPath)
	seenDir := make(map[string]bool)
	for _, spec := range matchedSpecs {
		// srcPath is copied by CopySpecsToDir()
		srcPath := rebasedDir.Join(ctx, spec.RelPathInPackage())
		destPath := rebasedDir.Join(ctx, spec.RelPathInPackage()+".fsv_meta")
		destDir := filepath.Dir(destPath.String())
		if _, ok := seenDir[destDir]; !ok {
			seenDir[destDir] = true
			sb.WriteString(fmt.Sprintf("mkdir -p %s\n", destDir))
		}
		sb.WriteString(fmt.Sprintf("%s --fsverity-path %s --signature none --hash-alg sha256 --output %s %s\n",
			metadataGeneratorPath.String(), fsverityPath.String(), destPath.String(), srcPath.String()))
	}

	// STEP 2: generate signed BuildManifest.apk
	// STEP 2-1: generate build_manifest.pb
	assetsPath := android.PathForModuleOut(ctx, "fsverity_manifest/assets")
	manifestPbPath := assetsPath.Join(ctx, "build_manifest.pb")
	manifestGeneratorPath := ctx.Config().HostToolPath(ctx, "fsverity_manifest_generator")
	cmd.Implicit(manifestGeneratorPath)
	sb.WriteString(fmt.Sprintf("rm -rf %s; mkdir -p %s\n", assetsPath.String(), assetsPath.String()))
	sb.WriteString(fmt.Sprintf("%s ", manifestGeneratorPath.String()))
	sb.WriteString(fmt.Sprintf("--fsverity-path %s ", fsverityPath.String()))
	sb.WriteString(fmt.Sprintf("--base-dir %s ", rootDir.String()))
	sb.WriteString(fmt.Sprintf("--output %s ", manifestPbPath.String()))

	manifestGeneratorRspPath := android.PathForModuleOut(ctx, "fsverity_manifest.rsp")
	f.writeManifestGeneratorRspFile(ctx, manifestGeneratorRspPath.OutputPath, matchedSpecs, rebasedDir)
	sb.WriteString(fmt.Sprintf("@%s\n", manifestGeneratorRspPath.String()))
	cmd.Implicit(manifestGeneratorRspPath)

	// STEP 2-2: generate BuildManifest.apk (unsigned)
	aapt2Path := ctx.Config().HostToolPath(ctx, "aapt2")
	apkPath := rebasedDir.Join(ctx, "etc", "security", "fsverity", "BuildManifest.apk")
	manifestTemplatePath := android.PathForSource(ctx, "system/security/fsverity/AndroidManifest.xml")
	// package-export is currently generated by Makefile.
	// TODO(b/330282551): fully migrate into Soong
	frameworkResPath := android.PathForArbitraryOutput(ctx, "target/common/obj/APPS/framework-res_intermediates/package-export.apk")
	cmd.Implicit(aapt2Path)
	cmd.Implicit(manifestTemplatePath)
	cmd.Implicit(frameworkResPath)

	sb.WriteString(fmt.Sprintf("%s link -o %s ", aapt2Path.String(), apkPath.String()))
	sb.WriteString(fmt.Sprintf("-A %s ", assetsPath.String()))
	sb.WriteString(fmt.Sprintf("-I %s ", frameworkResPath.String()))
	minSdkVersion := ctx.Config().PlatformSdkCodename()
	if minSdkVersion == "REL" {
		minSdkVersion = ctx.Config().PlatformSdkVersion().String()
	}
	sb.WriteString(fmt.Sprintf("--min-sdk-version %s ", minSdkVersion))
	sb.WriteString(fmt.Sprintf("--version-code %s ", ctx.Config().PlatformSdkVersion().String()))
	sb.WriteString(fmt.Sprintf("--version-name %s ", ctx.Config().AppsDefaultVersionName()))
	sb.WriteString(fmt.Sprintf("--manifest %s ", manifestTemplatePath.String()))
	sb.WriteString(fmt.Sprintf("--rename-manifest-package com.android.security.fsverity_metadata.%s\n", f.partitionName()))

	// STEP 2-3: sign BuildManifest.apk
	apksignerPath := ctx.Config().HostToolPath(ctx, "apksigner")
	pemPath, keyPath := ctx.Config().DefaultAppCertificate(ctx)
	cmd.Implicit(apksignerPath)
	cmd.Implicit(pemPath)
	cmd.Implicit(keyPath)
	sb.WriteString(fmt.Sprintf("%s sign ", apksignerPath.String()))
	sb.WriteString(fmt.Sprintf("--in %s ", apkPath.String()))
	sb.WriteString(fmt.Sprintf("--cert %s ", pemPath.String()))
	sb.WriteString(fmt.Sprintf("--key %s\n", keyPath.String()))

	android.WriteExecutableFileRuleVerbatim(ctx, fsverityBuilderPath, sb.String())
}
