// Copyright 2023 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package genrule

import (
	"android/soong/android"
)

var (
	DepfileAllowList = []string{
		"darwinn2_vndk_hal_command_message_generated_h_all_chips",
		"darwinn2_vndk_hal_common_types_generated_h_all_chips",
		"darwinn2_vndk_hal_graph_container_generated_h_all_chips",
		"darwinn2_vndk_hal_graph_generated_h_all_chips",
		"darwinn2_vndk_hal_reply_message_generated_h_all_chips",
		"darwinn2_vndk_hal_vii_commands_generated_h_all_chips",
		"depfile_allowed_for_test",
		"gen_uwb_core_proto",
		"libtextclassifier_fbgen_actions_actions-entity-data",
		"libtextclassifier_fbgen_actions_actions_model",
		"libtextclassifier_fbgen_annotator_datetime_datetime",
		"libtextclassifier_fbgen_annotator_entity-data",
		"libtextclassifier_fbgen_annotator_experimental_experimental",
		"libtextclassifier_fbgen_annotator_model",
		"libtextclassifier_fbgen_annotator_person_name_person_name_model",
		"libtextclassifier_fbgen_lang_id_common_flatbuffers_embedding-network",
		"libtextclassifier_fbgen_lang_id_common_flatbuffers_model",
		"libtextclassifier_fbgen_utils_codepoint-range",
		"libtextclassifier_fbgen_utils_container_bit-vector",
		"libtextclassifier_fbgen_utils_flatbuffers_flatbuffers",
		"libtextclassifier_fbgen_utils_flatbuffers_flatbuffers_test",
		"libtextclassifier_fbgen_utils_grammar_rules",
		"libtextclassifier_fbgen_utils_grammar_semantics_expression",
		"libtextclassifier_fbgen_utils_grammar_testing_value",
		"libtextclassifier_fbgen_utils_i18n_language-tag",
		"libtextclassifier_fbgen_utils_intents_intent-config",
		"libtextclassifier_fbgen_utils_lua_utils_tests",
		"libtextclassifier_fbgen_utils_normalization",
		"libtextclassifier_fbgen_utils_resources",
		"libtextclassifier_fbgen_utils_tflite_text_encoder_config",
		"libtextclassifier_fbgen_utils_tokenizer",
		"libtextclassifier_fbgen_utils_zlib_buffer",
		"tflite_support_metadata_schema",
		"tflite_support_spm_config",
		"tflite_support_spm_encoder_config",
	}

	SandboxingExcludedModuleList = []string{
		"AudioFocusControlProtoStub_cc",
		"AudioFocusControlProtoStub_h",
		"BlueberryFacadeAndCertGeneratedStub_py",
		"BlueberryFacadeGeneratedStub_cc",
		"BlueberryFacadeGeneratedStub_h",
		"BluetoothGeneratedDumpsysBinarySchema_bfbs",
		"BluetoothGeneratedDumpsysDataSchema_h",
		"CtsRenderscriptTestCases-rscript",
		"CtsRsBlasTestCases-rscript",
		"DumpstateServerProtoStub_cc",
		"DumpstateServerProtoStub_h",
		"FrontendStub_cc",
		"FrontendStub_h",
		"ImageProcessing-rscript",
		"ImageProcessing2-rscript",
		"ImageProcessingJB-rscript",
		"OpenwrtControlServerProto_cc",
		"OpenwrtControlServerProto_h",
		"RSTest-rscript",
		"RSTest_v11-rscript",
		"RSTest_v14-rscript",
		"RSTest_v16-rscript",
		"Refocus-rscript",
		"RsBalls-rscript",
		"ScriptGroupTest-rscript",
		"TracingVMProtoStub_cc",
		"TracingVMProtoStub_h",
		"VehicleServerProtoStub_cc",
		"VehicleServerProtoStub_cc@2.0-grpc-trout",
		"VehicleServerProtoStub_cc@default-grpc",
		"VehicleServerProtoStub_h",
		"VehicleServerProtoStub_h@2.0-grpc-trout",
		"VehicleServerProtoStub_h@default-grpc",
		"WmediumdServerProto_cc",
		"WmediumdServerProto_h",
		"android-support-multidex-instrumentation-version",
		"android-support-multidex-version",
		"batterystate-binarypb",
		"c2hal_test_genc++",
		"c2hal_test_genc++_headers",
		"call-binarypb",
		"checkIn-service-stub-lite",
		"chre_atoms_log.h",
		"com.android.apex.test.bar_stripped",
		"com.android.apex.test.baz_stripped",
		"com.android.apex.test.foo_stripped",
		"com.android.apex.test.pony_stripped",
		"com.android.apex.test.sharedlibs_generated",
		"com.android.apex.test.sharedlibs_secondary_generated",
		"com.fingerprints.extension@2.0_genc++",
		"com.fingerprints.extension@2.0_genc++_headers",
		"complication-providers-binarypb",
		"configs",
		"framework-cppstream-protos",
		"framework-javastream-protos",
		"google-check-in-service-stub-lite",
		"hardware.qorvo.uwb-service-version",
		"hidl2aidl_test_gen_aidl",
		"hidl2aidl_translate_cpp_test_gen_headers",
		"hidl2aidl_translate_cpp_test_gen_src",
		"hidl2aidl_translate_java_test_gen_src",
		"hidl2aidl_translate_ndk_test_gen_headers",
		"hidl2aidl_translate_ndk_test_gen_src",
		"hidl_cpp_impl_test_gen-headers",
		"hidl_error_test_gen",
		"hidl_export_test_gen-headers",
		"hidl_format_test_diff",
		"hidl_hash_test_gen",
		"hidl_hash_version_gen",
		"installed-app-binarypb",
		"libbt_topshim_facade_py_proto",
		"lock-screen-configuration-binarypb",
		"ltp_config_arm",
		"ltp_config_arm_64",
		"ltp_config_arm_64_hwasan",
		"ltp_config_arm_lowmem",
		"ltp_config_riscv_64",
		"ltp_config_x86_64",
		"nast",
		"nlproxy_proto_cc",
		"nlproxy_proto_h",
		"nos_app_avb_service_genc++",
		"nos_app_avb_service_genc++_headers",
		"nos_app_avb_service_genc++_mock",
		"nos_app_identity_service_genc++",
		"nos_app_identity_service_genc++_headers",
		"nos_app_identity_service_genc++_mock",
		"nos_app_keymaster_service_genc++",
		"nos_app_keymaster_service_genc++_headers",
		"nos_app_keymaster_service_genc++_mock",
		"nos_app_weaver_service_genc++",
		"nos_app_weaver_service_genc++_headers",
		"nos_app_weaver_service_genc++_mock",
		"nos_generator_test_service_genc++",
		"nos_generator_test_service_genc++_headers",
		"nos_generator_test_service_genc++_mock",
		"pandora-python-gen-src",
		"pandora_experimental-python-gen-src",
		"permissionsync-binarypb",
		"pvmfw_fdt_template_rs",
		"pw_log_log_proto_pwpb_h",
		"pw_tokenizer_proto_options_pwpb_h",
		"r8retrace-run-retrace",
		"remoteevent-binarypb",
		"seller-frontend-service-stub-lite",
		"services-gen-srcjar",
		"settings-lock-screen-binarypb",
		"settings-lock-status-binarypb",
		"settings-muted-apps-binarypb",
		"settings-phone-info-binarypb",
		"settings-supported-locales-binarypb",
		"settings-time-binarypb",
		"tiles-binarypb",
		"usagedata-binarypb",
		"uwbmac-version",
		"vendor_chre_atoms_log.h",
		"vendor_google_testing_pts_tests_audio_external_yaml",
		"vendor_pixelatoms_defs.h",
		"vm-tests-tf-lib",
		"watchfaces-active-binarypb",
		"watchfaces-favorites-binarypb",
		"watchfaces-flavors-flavors-binarypb",
		"wpan-mcps-version",
	}

	SandboxingExcludedPathList = []string{
		"art/test",
		"external/perfetto",
	}
)
var DepfileAllowSet = map[string]bool{}
var SandboxingExcludedModuleSet = map[string]bool{}
var SandboxingExcludedPathSet = map[string]bool{}

func init() {
	android.AddToStringSet(DepfileAllowSet, DepfileAllowList)
	android.AddToStringSet(SandboxingExcludedModuleSet, append(DepfileAllowList, SandboxingExcludedModuleList...))
	android.AddToStringSet(SandboxingExcludedPathSet, SandboxingExcludedPathList)
}
