// Copyright 2021 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bp2build

import (
	"android/soong/android"
	"fmt"

	"github.com/google/blueprint"
)

// Generates the base files which includes the base WORKSPACE marker file as well
// as the requisite rule files for the prebuilts workspace.
func GenerateSyntheticWorkspaceBaseFiles(ctx *CodegenContext) []BazelFile {
	var files []BazelFile

	// Ensure that the workspace is seen independently.
	files = append(files, newFile("", "WORKSPACE", ""))

	// Create a BUILD file for the rules imported from the main repository.
	files = append(files, newFile("build/bazel/rules", GeneratedBuildFileName, ""))

	// Import the Bazel rules required from the main repository.
	var c string
	var err error

	c, err = android.LoadBazelRuleDefinition(ctx.config, "soong_import")
	if err != nil {
		panic(err)
	} else {
		files = append(files, newFile("build/bazel/rules", "soong_import.bzl", c))
	}

	c, err = android.LoadBazelRuleDefinition(ctx.config, "soong_test_import")
	if err != nil {
		panic(err)
	} else {
		files = append(files, newFile("build/bazel/rules", "soong_test_import.bzl", c))
	}

	return files
}

// Generates the synthetic Bazel targets for all modules that are marked as
// bazel_module: { generate_synthetic_target: true }
func GenerateSyntheticBazelTargets(ctx *CodegenContext) (map[string]BazelTargets, CodegenMetrics) {
	buildFileToTargets := make(map[string]BazelTargets)

	metrics := CodegenMetrics{
		RuleClassCount: make(map[string]int),
	}

	dirs := make(map[string]bool)

	bpCtx := ctx.Context()
	bpCtx.VisitAllModules(func(m blueprint.Module) {
		dir := bpCtx.ModuleDir(m)
		dirs[dir] = true

		var t BazelTarget

		switch ctx.Mode() {
		case Bp2Build:
			if b, ok := m.(android.Bazelable); ok && b.GenerateSyntheticTarget() {
				ruleClass := b.GetSyntheticTargetRuleClass()

				metrics.RuleClassCount[ruleClass] += 1

				targetName := targetNameForBp2Build(bpCtx, m)

				t = BazelTarget{
					name:            targetNameForBp2Build(bpCtx, m),
					ruleClass:       ruleClass,
					bzlLoadLocation: fmt.Sprintf("//build/bazel/rules:%s.bzl", ruleClass),
					content: fmt.Sprintf(
						"%s(name=\"%s\", files=glob([\"%s/**/*\"]))",
						ruleClass,
						targetName,
						targetName,
					),
				}
			}

			buildFileToTargets[dir] = append(buildFileToTargets[dir], t)
		case QueryView:
			// Do nothing as this isn't required for QueryView.
		default:
			panic(fmt.Errorf("Unknown code-generation mode: %s", ctx.Mode()))
		}
	})

	return buildFileToTargets, metrics
}

func GenerateWorkspaceFileWithSyntheticWorkspaceReference(ctx *CodegenContext) BazelFile {
	ws, err := android.LoadBazelWorkspaceFile(ctx.config)

	if err != nil {
		panic(fmt.Errorf("Error while attempting to generate WORKSPACE file: %+v", err))
	}

	ws += "\n\n" +
		"# DO NOT SUBMIT: The following addition to the workspace file\n" +
		"# is only meant to be used in the context of the symlink workspace\n" +
		"# generated by bp2build and should not be checked in.\n" +
		"\n" +
		"local_repository(\n" +
		"    name = \"soong_prebuilts\",\n" +
		"    path = \"out/soong/workspace-prebuilts\"\n" +
		")\n"
	return newFile("", "WORKSPACE", ws)
}
