// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build_error.proto

package soong_build_error_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildError struct {
	// List of error messages of the overall build.
	ErrorMessages []string `protobuf:"bytes,1,rep,name=error_messages,json=errorMessages" json:"error_messages,omitempty"`
	// List of build action errors.
	ActionErrors         []*BuildActionError `protobuf:"bytes,2,rep,name=action_errors,json=actionErrors" json:"action_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BuildError) Reset()         { *m = BuildError{} }
func (m *BuildError) String() string { return proto.CompactTextString(m) }
func (*BuildError) ProtoMessage()    {}
func (*BuildError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2e15b05802a5501, []int{0}
}

func (m *BuildError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildError.Unmarshal(m, b)
}
func (m *BuildError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildError.Marshal(b, m, deterministic)
}
func (m *BuildError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildError.Merge(m, src)
}
func (m *BuildError) XXX_Size() int {
	return xxx_messageInfo_BuildError.Size(m)
}
func (m *BuildError) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildError.DiscardUnknown(m)
}

var xxx_messageInfo_BuildError proto.InternalMessageInfo

func (m *BuildError) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

func (m *BuildError) GetActionErrors() []*BuildActionError {
	if m != nil {
		return m.ActionErrors
	}
	return nil
}

// Build is composed of a list of build action. There can be a set of build
// actions that can failed.
type BuildActionError struct {
	// Description of the command.
	Description *string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// The command that raised the error.
	Command *string `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	// Any additional output from the executed command.
	Output *string `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	// The error string that failed the build.
	Error                *string  `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildActionError) Reset()         { *m = BuildActionError{} }
func (m *BuildActionError) String() string { return proto.CompactTextString(m) }
func (*BuildActionError) ProtoMessage()    {}
func (*BuildActionError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2e15b05802a5501, []int{1}
}

func (m *BuildActionError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildActionError.Unmarshal(m, b)
}
func (m *BuildActionError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildActionError.Marshal(b, m, deterministic)
}
func (m *BuildActionError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildActionError.Merge(m, src)
}
func (m *BuildActionError) XXX_Size() int {
	return xxx_messageInfo_BuildActionError.Size(m)
}
func (m *BuildActionError) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildActionError.DiscardUnknown(m)
}

var xxx_messageInfo_BuildActionError proto.InternalMessageInfo

func (m *BuildActionError) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *BuildActionError) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *BuildActionError) GetOutput() string {
	if m != nil && m.Output != nil {
		return *m.Output
	}
	return ""
}

func (m *BuildActionError) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildError)(nil), "soong_build_error.BuildError")
	proto.RegisterType((*BuildActionError)(nil), "soong_build_error.BuildActionError")
}

func init() { proto.RegisterFile("build_error.proto", fileDescriptor_a2e15b05802a5501) }

var fileDescriptor_a2e15b05802a5501 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2a, 0xcd, 0xcc,
	0x49, 0x89, 0x4f, 0x2d, 0x2a, 0xca, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c,
	0xce, 0xcf, 0xcf, 0x4b, 0x8f, 0x47, 0x92, 0x50, 0xaa, 0xe5, 0xe2, 0x72, 0x02, 0x71, 0x5d, 0x41,
	0x3c, 0x21, 0x55, 0x2e, 0x3e, 0xb0, 0x70, 0x7c, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x6a, 0xb1,
	0x04, 0xa3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x2f, 0x58, 0xd4, 0x17, 0x2a, 0x28, 0xe4, 0xc1, 0xc5,
	0x9b, 0x98, 0x5c, 0x92, 0x99, 0x9f, 0x07, 0x31, 0xa4, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x59, 0x0f, 0xc3, 0x7c, 0x3d, 0xb0, 0xe1, 0x8e, 0x60, 0xc5, 0x60, 0x2b, 0x82, 0x78, 0x12,
	0x11, 0x9c, 0x62, 0xa5, 0x1a, 0x2e, 0x01, 0x74, 0x15, 0x42, 0x0a, 0x5c, 0xdc, 0x29, 0xa9, 0xc5,
	0xc9, 0x45, 0x99, 0x05, 0x20, 0x31, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x64, 0x21, 0x21,
	0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xdc, 0xdc, 0xc4, 0xbc, 0x14, 0x09, 0x26, 0xb0, 0x2c, 0x8c, 0x2b,
	0x24, 0xc6, 0xc5, 0x96, 0x5f, 0x5a, 0x52, 0x50, 0x5a, 0x22, 0xc1, 0x0c, 0x96, 0x80, 0xf2, 0x84,
	0x44, 0xb8, 0x58, 0xc1, 0xee, 0x91, 0x60, 0x01, 0x0b, 0x43, 0x38, 0x4e, 0x92, 0x51, 0xe2, 0x18,
	0x2e, 0x8e, 0x07, 0x07, 0x15, 0x20, 0x00, 0x00, 0xff, 0xff, 0x40, 0xcd, 0x6c, 0x9b, 0x3e, 0x01,
	0x00, 0x00,
}
