// Copyright 2023 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aconfig

import (
	"android/soong/android"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/google/blueprint"
)

type AconfigReleaseConfigValue struct {
	ReleaseConfig string
	Values        []string `blueprint:"mutated"`
}

type DeclarationsModule struct {
	android.ModuleBase
	android.DefaultableModuleBase
	blueprint.IncrementalModule

	// Properties for "aconfig_declarations"
	properties struct {
		// aconfig files, relative to this Android.bp file
		Srcs []string `android:"path"`

		// Release config flag package
		Package string

		// Values for release configs / RELEASE_ACONFIG_VALUE_SETS
		// The current release config is `ReleaseConfig: ""`, others
		// are from RELEASE_ACONFIG_EXTRA_RELEASE_CONFIGS.
		ReleaseConfigValues []AconfigReleaseConfigValue

		// Container(system/system_ext/vendor/apex) that this module belongs to
		Container string

		// The flags will only be repackaged if this prop is true.
		Exportable bool
	}
}

func DeclarationsFactory() android.Module {
	module := &DeclarationsModule{}

	android.InitAndroidModule(module)
	android.InitDefaultableModule(module)
	module.AddProperties(&module.properties)

	return module
}

type implicitValuesTagType struct {
	blueprint.BaseDependencyTag

	// The release config name for these values.
	// Empty string for the actual current release config.
	ReleaseConfig string
}

var implicitValuesTag = implicitValuesTagType{}

func (module *DeclarationsModule) DepsMutator(ctx android.BottomUpMutatorContext) {
	// Validate Properties
	if len(module.properties.Srcs) == 0 {
		ctx.PropertyErrorf("srcs", "missing source files")
		return
	}
	if len(module.properties.Package) == 0 {
		ctx.PropertyErrorf("package", "missing package property")
	}
	if len(module.properties.Container) == 0 {
		ctx.PropertyErrorf("container", "missing container property")
	}

	// Add a dependency on the aconfig_value_sets defined in
	// RELEASE_ACONFIG_VALUE_SETS, and add any aconfig_values that
	// match our package.
	valuesFromConfig := ctx.Config().ReleaseAconfigValueSets()
	if len(valuesFromConfig) > 0 {
		ctx.AddDependency(ctx.Module(), implicitValuesTag, valuesFromConfig...)
	}
	for rcName, valueSets := range ctx.Config().ReleaseAconfigExtraReleaseConfigsValueSets() {
		if len(valueSets) > 0 {
			ctx.AddDependency(ctx.Module(), implicitValuesTagType{ReleaseConfig: rcName}, valueSets...)
		}
	}
}

func joinAndPrefix(prefix string, values []string) string {
	var sb strings.Builder
	for _, v := range values {
		sb.WriteString(prefix)
		sb.WriteString(v)
	}
	return sb.String()
}

func optionalVariable(prefix string, value string) string {
	var sb strings.Builder
	if value != "" {
		sb.WriteString(prefix)
		sb.WriteString(value)
	}
	return sb.String()
}

// Assemble the actual filename.
// If `rcName` is not empty, then insert "-{rcName}" into the path before the
// file extension.
func assembleFileName(rcName, path string) string {
	if rcName == "" {
		return path
	}
	dir, file := filepath.Split(path)
	rcName = "-" + rcName
	ext := filepath.Ext(file)
	base := file[:len(file)-len(ext)]
	return dir + base + rcName + ext
}

func (module *DeclarationsModule) GenerateAndroidBuildActions(ctx android.ModuleContext) {
	// Determine which release configs we are processing.
	//
	// We always process the current release config (empty string).
	// We may have been told to also create artifacts for some others.
	configs := append([]string{""}, ctx.Config().ReleaseAconfigExtraReleaseConfigs()...)
	slices.Sort(configs)

	values := make(map[string][]string)
	valuesFiles := make(map[string][]android.Path, 0)
	providerData := android.AconfigReleaseDeclarationsProviderData{}
	ctx.VisitDirectDeps(func(dep android.Module) {
		if depData, ok := android.OtherModuleProvider(ctx, dep, valueSetProviderKey); ok {
			depTag := ctx.OtherModuleDependencyTag(dep)
			for _, config := range configs {
				tag := implicitValuesTagType{ReleaseConfig: config}
				if depTag == tag {
					paths, ok := depData.AvailablePackages[module.properties.Package]
					if ok {
						valuesFiles[config] = append(valuesFiles[config], paths...)
						for _, path := range paths {
							values[config] = append(values[config], path.String())
						}
					}
				}
			}
		}
	})
	for _, config := range configs {
		module.properties.ReleaseConfigValues = append(module.properties.ReleaseConfigValues, AconfigReleaseConfigValue{
			ReleaseConfig: config,
			Values:        values[config],
		})

		// Intermediate format
		declarationFiles := android.PathsForModuleSrc(ctx, module.properties.Srcs)
		intermediateCacheFilePath := android.PathForModuleOut(ctx, assembleFileName(config, "intermediate.pb"))
		var defaultPermission string
		defaultPermission = ctx.Config().ReleaseAconfigFlagDefaultPermission()
		if config != "" {
			if confPerm, ok := ctx.Config().GetBuildFlag("RELEASE_ACONFIG_FLAG_DEFAULT_PERMISSION_" + config); ok {
				defaultPermission = confPerm
			}
		}
		var allowReadWrite bool
		if requireAllReadOnly, ok := ctx.Config().GetBuildFlag("RELEASE_ACONFIG_REQUIRE_ALL_READ_ONLY"); ok {
			// The build flag (RELEASE_ACONFIG_REQUIRE_ALL_READ_ONLY) is the negation of the aconfig flag
			// (allow-read-write) for historical reasons.
			// Bool build flags are always "" for false, and generally "true" for true.
			allowReadWrite = requireAllReadOnly == ""
		}
		inputFiles := make([]android.Path, len(declarationFiles))
		copy(inputFiles, declarationFiles)
		inputFiles = append(inputFiles, valuesFiles[config]...)
		args := map[string]string{
			"release_version":    ctx.Config().ReleaseVersion(),
			"package":            module.properties.Package,
			"declarations":       android.JoinPathsWithPrefix(declarationFiles, "--declarations "),
			"values":             joinAndPrefix(" --values ", values[config]),
			"default-permission": optionalVariable(" --default-permission ", defaultPermission),
			"allow-read-write":   optionalVariable(" --allow-read-write ", strconv.FormatBool(allowReadWrite)),
		}
		if len(module.properties.Container) > 0 {
			args["container"] = "--container " + module.properties.Container
		}
		ctx.Build(pctx, android.BuildParams{
			Rule:        aconfigRule,
			Output:      intermediateCacheFilePath,
			Inputs:      inputFiles,
			Description: "aconfig_declarations",
			Args:        args,
		})

		intermediateDumpFilePath := android.PathForModuleOut(ctx, assembleFileName(config, "intermediate.txt"))
		ctx.Build(pctx, android.BuildParams{
			Rule:        aconfigTextRule,
			Output:      intermediateDumpFilePath,
			Inputs:      android.Paths{intermediateCacheFilePath},
			Description: "aconfig_text",
		})

		providerData[config] = android.AconfigDeclarationsProviderData{
			Package:                     module.properties.Package,
			Container:                   module.properties.Container,
			Exportable:                  module.properties.Exportable,
			IntermediateCacheOutputPath: intermediateCacheFilePath,
			IntermediateDumpOutputPath:  intermediateDumpFilePath,
		}
	}
	android.SetProvider(ctx, android.AconfigDeclarationsProviderKey, providerData[""])
	android.SetProvider(ctx, android.AconfigReleaseDeclarationsProviderKey, providerData)
}

var _ blueprint.Incremental = &DeclarationsModule{}
//
// Created by sprin on 6/30/2023.
//

#include "AimKill.h"
#include "Il2Cpp.h"


void AimKill::TakeDamage_Req(uintptr_t  Player, uintptr_t  LocalPlayer, void * WeaponOnHan, int Damage, int WeaponID, COW_GamePlay_IHAAMHPPLMG_o PlayerID, Vector3 localLocation, Vector3 enemyLocation, monoList<float *>CheckParams)
{
    if(baseaddr){
            float Dist = Vector3::Distance(localLocation, enemyLocation);
                    if(Dist > 1){
                                auto ObjectPool = *(void **)((uintptr_t) LocalPlayer + offsets.weapon.GEGFCFDGGGP);
                                            if(ObjectPool)
                                                        {
                                                                        if(!isDamage)
                                                                                        {
                                                                                                            Global::Weapon::SetStartDamage(WeaponOnHan, ObjectPool);
                                                                                                                                isDamage = true;
                                                                                                                                                }
                                                                                                                                                                auto DamageInfo = Il2Cpp::NewClassObject(YK("Assembly-CSharp.dll"), YK("COW.GamePlay"), YK("ELMGJKHIIAA"));

                                                                                                                                                                                if (DamageInfo)
                                                                                                                                                                                                {
                                                                                                                                                                                                                    *(COW_GamePlay_IHAAMHPPLMG_o *) ((uintptr_t) DamageInfo + offsets.weapon.DHGCIEKPBFA) = PlayerID;
                                                                                                                                                                                                                                        *(int *) ((uintptr_t) DamageInfo + offsets.weapon.DBLBLKADCNP) = Damage;
                                                                                                                                                                                                                                                            *(int *) ((uintptr_t) DamageInfo + offsets.weapon.KENBMOOEHBG) = 1;
                                                                                                                                                                                                                                                                                *(bool *) ((uintptr_t) DamageInfo + offsets.weapon.NNNADMOFPIE) = true;//unknown
                                                                                                                                                                                                                                                                                                    *(bool *) ((uintptr_t) DamageInfo + offsets.weapon.MJIHLDJNHLF) = true;//unknown
                                                                                                                                                                                                                                                                                                                        *(void **) ((uintptr_t) DamageInfo + offsets.weapon.GPBDEDFKJNA) = WeaponOnHand; //Class Weapon
                                                                                                                                                                                                                                                                                                                                            *(Vector3 *) ((uintptr_t) DamageInfo + offsets.weapon.CNEICNJFGLM) = localLocation;
                                                                                                                                                                                                                                                                                                                                                                *(Vector3 *) ((uintptr_t) DamageInfo + offsets.weapon.HECJHKEDFEB) = enemyLocation;//Hitpos

                                                                                                                                                                                                                                                                                                                                                                                    auto AceWall =  *(monoDictionary<uint8_t*, void **> **)((uintptr_t) ObjectPool + offsets.mADMMIICBNN.FHLFLAHCIBN);
                                                                                                                                                                                                                                                                                                                                                                                                        if(AceWall)
                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    *(monoDictionary<uint8_t *, void **> **) ((uintptr_t) DamageInfo + offsets.weapon.FHLFLAHCIBN) = AceWall;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            *(byte *) ((uintptr_t) DamageInfo + offsets.weapon.ACAKHEABPEJ) =*(byte *) ((uintptr_t) ObjectPool + offsets.mADMMIICBNN.ACAKHEABPEJ) ;//unknown
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    *(Vector3 *) ((uintptr_t) DamageInfo +offsets.weapon.JNLGFLFLBHO) = *(Vector3 *) ((uintptr_t) ObjectPool + offsets.mADMMIICBNN.JNLGFLFLBHO);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            auto WeaponData =  *(void **) ((uintptr_t) WeaponOnHand+ offsets.weapon.LAEMLAPIAFD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(WeaponData){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        *(int *) ((uintptr_t) DamageInfo + offsets.weapon.PIAMIOFEBKF) = *(int *) ((uintptr_t) WeaponData +offsets.weapon.POBGKMDJMDC);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                auto damagerWeaponDynamicInfo = Il2Cpp::NewClassObject(YK("Assembly-CSharp.dll"), YK("COW.GamePlay"), YK("MKFEKBKJCKE"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (damagerWeaponDynamicInfo)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int TypeWeapon = Global::Weapon::GetTypeWeapon(WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(TypeWeapon !=3 && Dist > 1.0f) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (Global::Timer::get_time() >= TimerTakeDamageinit) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TimerTakeDamageinit = Global::Timer::get_time() + TimerTakeDamageEnd;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Global::Weapon::TakeDamage(Player, Damage, PlayerID, DamageInfo, WeaponID, localLocation, enemyLocation, CheckParams, damagerWeaponDynamicInfo, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Global::Weapon::StartWholeBodyFiring(LocalPlayer, WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Global::Weapon::StopFire(LocalPlayer, WeaponOnHand);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }else if (TypeWeapon == 3 ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Dist <= 1.0f) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Global::Timer::get_time() >= TimerTakeDamageinit) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TimerTakeDamageinit = Global::Timer::get_time() + TimerTakeDamageEnd;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Global::Weapon::TakeDamage(Player, Damage, PlayerID, DamageInfo, WeaponID, localLocation, enemyLocation, CheckParams, damagerWeaponDynamicInfo, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Global::Weapon::StartWholeBodyFiring(LocalPlayer, WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Global::Weapon::StopFire(LocalPlayer, WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           void AimKill::Start(Player LocalPlayer, Player EnemyPlayer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if(LocalPlayer.getObj() && EnemyPlayer.getObj()){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       baseaddr = Il2CppBase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               WeaponOnHand = Global::Weapon::GetWeaponOnHand(LocalPlayer.getObj());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if(WeaponOnHand)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           auto WeaponID = Global::Weapon::GetWeaponID(WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       auto PlayerID = *(COW_GamePlay_IHAAMHPPLMG_o*)((uintptr_t) LocalPlayer.getObj() + offsets.weapon.KFMGKCJMCAM);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   auto Damage = Global::Weapon::GetDamage(WeaponOnHand);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               auto CheckParams = *(monoList<float *> *)((uintptr_t) WeaponOnHand + offsets.weapon.PIGOIHAOJGH);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           TakeDamage_Req(EnemyPlayer.getObj(),LocalPlayer.getObj(),WeaponOnHand,Damage,WeaponID,PlayerID,LocalPlayer.getHeadPosition(),EnemyPlayer.getHeadPosition(),CheckParams);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       void AimKill::Stop() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           WeaponOnHand = nullptr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }