// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

package metrics_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricsBase struct {
	// Unique timestamp generated when the build starts.
	BuildDateTimestamp *uint32 `protobuf:"varint,1,opt,name=build_date_timestamp,json=buildDateTimestamp" json:"build_date_timestamp,omitempty"`
	// It is usually used to specify the branch name [and release candidate].
	BuildId *string `protobuf:"bytes,2,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	// The platform version codename, eg. P, Q, REL.
	PlatformVersionCodename *string `protobuf:"bytes,3,opt,name=platform_version_codename,json=platformVersionCodename" json:"platform_version_codename,omitempty"`
	// The target product information, eg. aosp_arm.
	TargetProduct *string `protobuf:"bytes,4,opt,name=target_product,json=targetProduct" json:"target_product,omitempty"`
	// The target build variant information, eg. eng.
	TargetBuildVariant *string `protobuf:"bytes,5,opt,name=target_build_variant,json=targetBuildVariant" json:"target_build_variant,omitempty"`
	// The target build type information, eg. release.
	TargetBuildType *string `protobuf:"bytes,6,opt,name=target_build_type,json=targetBuildType" json:"target_build_type,omitempty"`
	// The target arch information, eg. arm.
	TargetArch *string `protobuf:"bytes,7,opt,name=target_arch,json=targetArch" json:"target_arch,omitempty"`
	// The target arch variant information, eg. armv7-a-neon.
	TargetArchVariant *string `protobuf:"bytes,8,opt,name=target_arch_variant,json=targetArchVariant" json:"target_arch_variant,omitempty"`
	// The target cpu variant information, eg. generic.
	TargetCpuVariant *string `protobuf:"bytes,9,opt,name=target_cpu_variant,json=targetCpuVariant" json:"target_cpu_variant,omitempty"`
	// The host arch information, eg. x86_64.
	HostArch *string `protobuf:"bytes,10,opt,name=host_arch,json=hostArch" json:"host_arch,omitempty"`
	// The host 2nd arch information, eg. x86.
	Host_2NdArch *string `protobuf:"bytes,11,opt,name=host_2nd_arch,json=host2ndArch" json:"host_2nd_arch,omitempty"`
	// The host os information, eg. linux.
	HostOs *string `protobuf:"bytes,12,opt,name=host_os,json=hostOs" json:"host_os,omitempty"`
	// The host os extra information, eg. Linux-4.17.0-3rodete2-amd64-x86_64-Debian-GNU.
	HostOsExtra *string `protobuf:"bytes,13,opt,name=host_os_extra,json=hostOsExtra" json:"host_os_extra,omitempty"`
	// The host cross os information, eg. windows.
	HostCrossOs *string `protobuf:"bytes,14,opt,name=host_cross_os,json=hostCrossOs" json:"host_cross_os,omitempty"`
	// The host cross arch information, eg. x86.
	HostCrossArch *string `protobuf:"bytes,15,opt,name=host_cross_arch,json=hostCrossArch" json:"host_cross_arch,omitempty"`
	// The host cross 2nd arch information, eg. x86_64.
	HostCross_2NdArch *string `protobuf:"bytes,16,opt,name=host_cross_2nd_arch,json=hostCross2ndArch" json:"host_cross_2nd_arch,omitempty"`
	// The host build type information, eg. release.
	HostBuildType *string `protobuf:"bytes,17,opt,name=host_build_type,json=hostBuildType" json:"host_build_type,omitempty"`
	// The directory for generated built artifacts installation, eg. out.
	OutDir *string `protobuf:"bytes,18,opt,name=out_dir,json=outDir" json:"out_dir,omitempty"`
	// The metrics for calling various tools (microfactory) before Soong_UI starts.
	SetupTools []*PerfInfo `protobuf:"bytes,19,rep,name=setup_tools,json=setupTools" json:"setup_tools,omitempty"`
	// The metrics for calling various tools (finder, path_interposer) before sub-systems run.
	InitialTools []*PerfInfo `protobuf:"bytes,20,rep,name=initial_tools,json=initialTools" json:"initial_tools,omitempty"`
	// The metrics for calling Kati by multiple times.
	KatiRuns []*PerfInfo `protobuf:"bytes,21,rep,name=kati_runs,json=katiRuns" json:"kati_runs,omitempty"`
	// The metrics for calling Soong.
	SoongRuns []*PerfInfo `protobuf:"bytes,22,rep,name=soong_runs,json=soongRuns" json:"soong_runs,omitempty"`
	// The metrics for calling Ninja.
	NinjaRuns            []*PerfInfo `protobuf:"bytes,23,rep,name=ninja_runs,json=ninjaRuns" json:"ninja_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetricsBase) Reset()         { *m = MetricsBase{} }
func (m *MetricsBase) String() string { return proto.CompactTextString(m) }
func (*MetricsBase) ProtoMessage()    {}
func (*MetricsBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_2e66686eb4714c1d, []int{0}
}
func (m *MetricsBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsBase.Unmarshal(m, b)
}
func (m *MetricsBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsBase.Marshal(b, m, deterministic)
}
func (dst *MetricsBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsBase.Merge(dst, src)
}
func (m *MetricsBase) XXX_Size() int {
	return xxx_messageInfo_MetricsBase.Size(m)
}
func (m *MetricsBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsBase.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsBase proto.InternalMessageInfo

func (m *MetricsBase) GetBuildDateTimestamp() uint32 {
	if m != nil && m.BuildDateTimestamp != nil {
		return *m.BuildDateTimestamp
	}
	return 0
}

func (m *MetricsBase) GetBuildId() string {
	if m != nil && m.BuildId != nil {
		return *m.BuildId
	}
	return ""
}

func (m *MetricsBase) GetPlatformVersionCodename() string {
	if m != nil && m.PlatformVersionCodename != nil {
		return *m.PlatformVersionCodename
	}
	return ""
}

func (m *MetricsBase) GetTargetProduct() string {
	if m != nil && m.TargetProduct != nil {
		return *m.TargetProduct
	}
	return ""
}

func (m *MetricsBase) GetTargetBuildVariant() string {
	if m != nil && m.TargetBuildVariant != nil {
		return *m.TargetBuildVariant
	}
	return ""
}

func (m *MetricsBase) GetTargetBuildType() string {
	if m != nil && m.TargetBuildType != nil {
		return *m.TargetBuildType
	}
	return ""
}

func (m *MetricsBase) GetTargetArch() string {
	if m != nil && m.TargetArch != nil {
		return *m.TargetArch
	}
	return ""
}

func (m *MetricsBase) GetTargetArchVariant() string {
	if m != nil && m.TargetArchVariant != nil {
		return *m.TargetArchVariant
	}
	return ""
}

func (m *MetricsBase) GetTargetCpuVariant() string {
	if m != nil && m.TargetCpuVariant != nil {
		return *m.TargetCpuVariant
	}
	return ""
}

func (m *MetricsBase) GetHostArch() string {
	if m != nil && m.HostArch != nil {
		return *m.HostArch
	}
	return ""
}

func (m *MetricsBase) GetHost_2NdArch() string {
	if m != nil && m.Host_2NdArch != nil {
		return *m.Host_2NdArch
	}
	return ""
}

func (m *MetricsBase) GetHostOs() string {
	if m != nil && m.HostOs != nil {
		return *m.HostOs
	}
	return ""
}

func (m *MetricsBase) GetHostOsExtra() string {
	if m != nil && m.HostOsExtra != nil {
		return *m.HostOsExtra
	}
	return ""
}

func (m *MetricsBase) GetHostCrossOs() string {
	if m != nil && m.HostCrossOs != nil {
		return *m.HostCrossOs
	}
	return ""
}

func (m *MetricsBase) GetHostCrossArch() string {
	if m != nil && m.HostCrossArch != nil {
		return *m.HostCrossArch
	}
	return ""
}

func (m *MetricsBase) GetHostCross_2NdArch() string {
	if m != nil && m.HostCross_2NdArch != nil {
		return *m.HostCross_2NdArch
	}
	return ""
}

func (m *MetricsBase) GetHostBuildType() string {
	if m != nil && m.HostBuildType != nil {
		return *m.HostBuildType
	}
	return ""
}

func (m *MetricsBase) GetOutDir() string {
	if m != nil && m.OutDir != nil {
		return *m.OutDir
	}
	return ""
}

func (m *MetricsBase) GetSetupTools() []*PerfInfo {
	if m != nil {
		return m.SetupTools
	}
	return nil
}

func (m *MetricsBase) GetInitialTools() []*PerfInfo {
	if m != nil {
		return m.InitialTools
	}
	return nil
}

func (m *MetricsBase) GetKatiRuns() []*PerfInfo {
	if m != nil {
		return m.KatiRuns
	}
	return nil
}

func (m *MetricsBase) GetSoongRuns() []*PerfInfo {
	if m != nil {
		return m.SoongRuns
	}
	return nil
}

func (m *MetricsBase) GetNinjaRuns() []*PerfInfo {
	if m != nil {
		return m.NinjaRuns
	}
	return nil
}

type PerfInfo struct {
	// The description for the phase/action/part while the tool running.
	Desc *string `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	// The name for the running phase/action/part.
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The absolute start time.
	StartTime *uint64 `protobuf:"varint,3,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// The real running time.
	RealTime *uint64 `protobuf:"varint,4,opt,name=real_time,json=realTime" json:"real_time,omitempty"`
	// The memory use.
	MemoryUse            *uint64  `protobuf:"varint,5,opt,name=memory_use,json=memoryUse" json:"memory_use,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerfInfo) Reset()         { *m = PerfInfo{} }
func (m *PerfInfo) String() string { return proto.CompactTextString(m) }
func (*PerfInfo) ProtoMessage()    {}
func (*PerfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_2e66686eb4714c1d, []int{1}
}
func (m *PerfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerfInfo.Unmarshal(m, b)
}
func (m *PerfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerfInfo.Marshal(b, m, deterministic)
}
func (dst *PerfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerfInfo.Merge(dst, src)
}
func (m *PerfInfo) XXX_Size() int {
	return xxx_messageInfo_PerfInfo.Size(m)
}
func (m *PerfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PerfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PerfInfo proto.InternalMessageInfo

func (m *PerfInfo) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *PerfInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PerfInfo) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *PerfInfo) GetRealTime() uint64 {
	if m != nil && m.RealTime != nil {
		return *m.RealTime
	}
	return 0
}

func (m *PerfInfo) GetMemoryUse() uint64 {
	if m != nil && m.MemoryUse != nil {
		return *m.MemoryUse
	}
	return 0
}

type ModuleTypeInfo struct {
	// The module type, eg. java_library, cc_binary, and etc.
	ModuleType *string `protobuf:"bytes,1,opt,name=module_type,json=moduleType" json:"module_type,omitempty"`
	// The number of logical modules.
	NumOfModules         *uint32  `protobuf:"varint,2,opt,name=num_of_modules,json=numOfModules" json:"num_of_modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleTypeInfo) Reset()         { *m = ModuleTypeInfo{} }
func (m *ModuleTypeInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleTypeInfo) ProtoMessage()    {}
func (*ModuleTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_2e66686eb4714c1d, []int{2}
}
func (m *ModuleTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleTypeInfo.Unmarshal(m, b)
}
func (m *ModuleTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleTypeInfo.Marshal(b, m, deterministic)
}
func (dst *ModuleTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleTypeInfo.Merge(dst, src)
}
func (m *ModuleTypeInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleTypeInfo.Size(m)
}
func (m *ModuleTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleTypeInfo proto.InternalMessageInfo

func (m *ModuleTypeInfo) GetModuleType() string {
	if m != nil && m.ModuleType != nil {
		return *m.ModuleType
	}
	return ""
}

func (m *ModuleTypeInfo) GetNumOfModules() uint32 {
	if m != nil && m.NumOfModules != nil {
		return *m.NumOfModules
	}
	return 0
}

func init() {
	proto.RegisterType((*MetricsBase)(nil), "build_metrics.MetricsBase")
	proto.RegisterType((*PerfInfo)(nil), "build_metrics.PerfInfo")
	proto.RegisterType((*ModuleTypeInfo)(nil), "build_metrics.ModuleTypeInfo")
}

func init() { proto.RegisterFile("metrics.proto", fileDescriptor_metrics_2e66686eb4714c1d) }

var fileDescriptor_metrics_2e66686eb4714c1d = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x5f, 0x6f, 0xd3, 0x3c,
	0x18, 0xc5, 0xd5, 0x77, 0x7d, 0xd7, 0xe4, 0xc9, 0xd2, 0xad, 0xde, 0xa0, 0x99, 0xd0, 0xb4, 0xa9,
	0x02, 0x34, 0x21, 0xa8, 0xd0, 0x84, 0x10, 0x42, 0xdc, 0xb0, 0x0d, 0x89, 0x5d, 0x4c, 0x9d, 0xa2,
	0x31, 0x24, 0x6e, 0x2c, 0x93, 0xb8, 0x9b, 0xa1, 0xb1, 0x23, 0xff, 0x99, 0xd8, 0x87, 0xe0, 0xcb,
	0xf2, 0x09, 0x90, 0x1f, 0x27, 0x69, 0x77, 0x33, 0xee, 0x9c, 0x73, 0x7e, 0xc7, 0x3e, 0x89, 0x63,
	0x43, 0x5a, 0x71, 0xab, 0x45, 0x61, 0xa6, 0xb5, 0x56, 0x56, 0x91, 0xf4, 0xbb, 0x13, 0x8b, 0x92,
	0x36, 0xe2, 0xe4, 0xcf, 0x00, 0x92, 0xf3, 0x30, 0x3e, 0x66, 0x86, 0x93, 0xd7, 0xb0, 0x13, 0x80,
	0x92, 0x59, 0x4e, 0xad, 0xa8, 0xb8, 0xb1, 0xac, 0xaa, 0xb3, 0xde, 0x41, 0xef, 0x30, 0xcd, 0x09,
	0x7a, 0xa7, 0xcc, 0xf2, 0xcb, 0xd6, 0x21, 0xbb, 0x10, 0x85, 0x84, 0x28, 0xb3, 0xff, 0x0e, 0x7a,
	0x87, 0x71, 0x3e, 0xc0, 0xe7, 0xb3, 0x92, 0xbc, 0x87, 0xdd, 0x7a, 0xc1, 0xec, 0x5c, 0xe9, 0x8a,
	0xde, 0x72, 0x6d, 0x84, 0x92, 0xb4, 0x50, 0x25, 0x97, 0xac, 0xe2, 0xd9, 0x1a, 0xb2, 0xe3, 0x16,
	0xb8, 0x0a, 0xfe, 0x49, 0x63, 0x93, 0x67, 0x30, 0xb4, 0x4c, 0x5f, 0x73, 0x4b, 0x6b, 0xad, 0x4a,
	0x57, 0xd8, 0xac, 0x8f, 0x81, 0x34, 0xa8, 0x17, 0x41, 0xf4, 0x7d, 0x1b, 0x2c, 0x94, 0xb8, 0x65,
	0x5a, 0x30, 0x69, 0xb3, 0xff, 0x11, 0x26, 0xc1, 0x3b, 0xf6, 0xd6, 0x55, 0x70, 0xc8, 0x0b, 0x18,
	0xdd, 0x4b, 0xd8, 0xbb, 0x9a, 0x67, 0xeb, 0x88, 0x6f, 0xae, 0xe0, 0x97, 0x77, 0x35, 0x27, 0xfb,
	0x90, 0x34, 0x2c, 0xd3, 0xc5, 0x4d, 0x36, 0x40, 0x0a, 0x82, 0xf4, 0x51, 0x17, 0x37, 0x64, 0x0a,
	0xdb, 0x2b, 0x40, 0xb7, 0x7a, 0x84, 0xe0, 0x68, 0x09, 0xb6, 0x8b, 0xbf, 0x84, 0xa6, 0x12, 0x2d,
	0x6a, 0xd7, 0xe1, 0x31, 0xe2, 0x5b, 0xc1, 0x39, 0xa9, 0x5d, 0x4b, 0x3f, 0x81, 0xf8, 0x46, 0x99,
	0x66, 0x71, 0x40, 0x28, 0xf2, 0x02, 0x2e, 0x3d, 0x81, 0x14, 0xcd, 0x23, 0x59, 0x06, 0x20, 0x41,
	0x20, 0xf1, 0xe2, 0x91, 0x2c, 0x91, 0x19, 0xc3, 0x00, 0x19, 0x65, 0xb2, 0x0d, 0x74, 0xd7, 0xfd,
	0xe3, 0xcc, 0x74, 0x61, 0x65, 0x28, 0xff, 0x65, 0x35, 0xcb, 0xd2, 0x65, 0x78, 0x66, 0x3e, 0x79,
	0xa9, 0x63, 0x0a, 0xad, 0x8c, 0xf1, 0x53, 0x0c, 0x97, 0xcc, 0x89, 0xd7, 0x66, 0x86, 0x3c, 0x87,
	0xcd, 0x15, 0x06, 0x6b, 0x6c, 0x86, 0x6d, 0xea, 0x28, 0x2c, 0xf2, 0x0a, 0xb6, 0x57, 0xb8, 0xae,
	0xf2, 0x56, 0x78, 0xf1, 0x8e, 0x6d, 0x7b, 0xb7, 0xd3, 0xae, 0xec, 0xd0, 0x68, 0x39, 0xed, 0x72,
	0x7f, 0xc6, 0x30, 0x50, 0xce, 0xd2, 0x52, 0xe8, 0x8c, 0x84, 0xf7, 0x53, 0xce, 0x9e, 0x0a, 0x4d,
	0xde, 0x41, 0x62, 0xb8, 0x75, 0x35, 0xb5, 0x4a, 0x2d, 0x4c, 0xb6, 0x7d, 0xb0, 0x76, 0x98, 0x1c,
	0x8d, 0xa7, 0xf7, 0xfe, 0xfd, 0xe9, 0x05, 0xd7, 0xf3, 0x33, 0x39, 0x57, 0x39, 0x20, 0x7b, 0xe9,
	0x51, 0xf2, 0x01, 0x52, 0x21, 0x85, 0x15, 0x6c, 0xd1, 0x64, 0x77, 0x1e, 0xce, 0x6e, 0x34, 0x74,
	0x48, 0xbf, 0x81, 0xf8, 0x27, 0xb3, 0x82, 0x6a, 0x27, 0x4d, 0xf6, 0xe8, 0xe1, 0x64, 0xe4, 0xc9,
	0xdc, 0x49, 0x43, 0xde, 0x02, 0x18, 0xa5, 0xe4, 0x75, 0x88, 0x3d, 0x7e, 0x38, 0x16, 0x23, 0xda,
	0xe6, 0xa4, 0x90, 0x3f, 0x58, 0xc8, 0x8d, 0xff, 0x91, 0x43, 0xd4, 0xe7, 0x26, 0xbf, 0x7b, 0x10,
	0xb5, 0x3a, 0x21, 0xd0, 0x2f, 0xb9, 0x29, 0xf0, 0x84, 0xc7, 0x39, 0x8e, 0xbd, 0x86, 0x67, 0x34,
	0x9c, 0x67, 0x1c, 0x93, 0x3d, 0x00, 0x63, 0x99, 0xb6, 0x78, 0x29, 0xe0, 0xe9, 0xed, 0xe7, 0x31,
	0x2a, 0xfe, 0x2e, 0xf0, 0xff, 0xaa, 0xe6, 0xfe, 0xa3, 0x79, 0xb7, 0x8f, 0x6e, 0xe4, 0x05, 0x34,
	0xf7, 0x00, 0x2a, 0x5e, 0x29, 0x7d, 0x47, 0x9d, 0xe1, 0x78, 0x36, 0xfb, 0x79, 0x1c, 0x94, 0x2f,
	0x86, 0x4f, 0xbe, 0xc2, 0xf0, 0x5c, 0x95, 0x6e, 0xc1, 0xfd, 0xa6, 0x62, 0xa9, 0x7d, 0x48, 0x2a,
	0x54, 0xc2, 0xe6, 0x87, 0x6e, 0x50, 0x75, 0x10, 0x79, 0x0a, 0x43, 0xe9, 0x2a, 0xaa, 0xe6, 0x34,
	0x88, 0x06, 0xbb, 0xa6, 0xf9, 0x86, 0x74, 0xd5, 0x6c, 0x1e, 0x66, 0x33, 0xc7, 0xa3, 0xcf, 0x6b,
	0xdf, 0xda, 0xfb, 0x8f, 0xe2, 0xfd, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0x85, 0x1e, 0x93, 0x55,
	0x0f, 0x05, 0x00, 0x00,
}
