// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

package metrics_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricsBase_BUILDVARIANT int32

const (
	MetricsBase_USER      MetricsBase_BUILDVARIANT = 0
	MetricsBase_USERDEBUG MetricsBase_BUILDVARIANT = 1
	MetricsBase_ENG       MetricsBase_BUILDVARIANT = 2
)

var MetricsBase_BUILDVARIANT_name = map[int32]string{
	0: "USER",
	1: "USERDEBUG",
	2: "ENG",
}
var MetricsBase_BUILDVARIANT_value = map[string]int32{
	"USER":      0,
	"USERDEBUG": 1,
	"ENG":       2,
}

func (x MetricsBase_BUILDVARIANT) Enum() *MetricsBase_BUILDVARIANT {
	p := new(MetricsBase_BUILDVARIANT)
	*p = x
	return p
}
func (x MetricsBase_BUILDVARIANT) String() string {
	return proto.EnumName(MetricsBase_BUILDVARIANT_name, int32(x))
}
func (x *MetricsBase_BUILDVARIANT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetricsBase_BUILDVARIANT_value, data, "MetricsBase_BUILDVARIANT")
	if err != nil {
		return err
	}
	*x = MetricsBase_BUILDVARIANT(value)
	return nil
}
func (MetricsBase_BUILDVARIANT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{0, 0}
}

type MetricsBase_TARGETARCH int32

const (
	MetricsBase_ARM    MetricsBase_TARGETARCH = 0
	MetricsBase_ARM64  MetricsBase_TARGETARCH = 1
	MetricsBase_X86    MetricsBase_TARGETARCH = 2
	MetricsBase_X86_64 MetricsBase_TARGETARCH = 3
)

var MetricsBase_TARGETARCH_name = map[int32]string{
	0: "ARM",
	1: "ARM64",
	2: "X86",
	3: "X86_64",
}
var MetricsBase_TARGETARCH_value = map[string]int32{
	"ARM":    0,
	"ARM64":  1,
	"X86":    2,
	"X86_64": 3,
}

func (x MetricsBase_TARGETARCH) Enum() *MetricsBase_TARGETARCH {
	p := new(MetricsBase_TARGETARCH)
	*p = x
	return p
}
func (x MetricsBase_TARGETARCH) String() string {
	return proto.EnumName(MetricsBase_TARGETARCH_name, int32(x))
}
func (x *MetricsBase_TARGETARCH) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetricsBase_TARGETARCH_value, data, "MetricsBase_TARGETARCH")
	if err != nil {
		return err
	}
	*x = MetricsBase_TARGETARCH(value)
	return nil
}
func (MetricsBase_TARGETARCH) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{0, 1}
}

type MetricsBase_HOSTARCH int32

const (
	MetricsBase_HOST_X86    MetricsBase_HOSTARCH = 0
	MetricsBase_HOST_X86_64 MetricsBase_HOSTARCH = 1
)

var MetricsBase_HOSTARCH_name = map[int32]string{
	0: "HOST_X86",
	1: "HOST_X86_64",
}
var MetricsBase_HOSTARCH_value = map[string]int32{
	"HOST_X86":    0,
	"HOST_X86_64": 1,
}

func (x MetricsBase_HOSTARCH) Enum() *MetricsBase_HOSTARCH {
	p := new(MetricsBase_HOSTARCH)
	*p = x
	return p
}
func (x MetricsBase_HOSTARCH) String() string {
	return proto.EnumName(MetricsBase_HOSTARCH_name, int32(x))
}
func (x *MetricsBase_HOSTARCH) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetricsBase_HOSTARCH_value, data, "MetricsBase_HOSTARCH")
	if err != nil {
		return err
	}
	*x = MetricsBase_HOSTARCH(value)
	return nil
}
func (MetricsBase_HOSTARCH) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{0, 2}
}

type ModuleTypeInfo_BUILDSYSTEM int32

const (
	ModuleTypeInfo_SOONG ModuleTypeInfo_BUILDSYSTEM = 0
	ModuleTypeInfo_MAKE  ModuleTypeInfo_BUILDSYSTEM = 1
)

var ModuleTypeInfo_BUILDSYSTEM_name = map[int32]string{
	0: "SOONG",
	1: "MAKE",
}
var ModuleTypeInfo_BUILDSYSTEM_value = map[string]int32{
	"SOONG": 0,
	"MAKE":  1,
}

func (x ModuleTypeInfo_BUILDSYSTEM) Enum() *ModuleTypeInfo_BUILDSYSTEM {
	p := new(ModuleTypeInfo_BUILDSYSTEM)
	*p = x
	return p
}
func (x ModuleTypeInfo_BUILDSYSTEM) String() string {
	return proto.EnumName(ModuleTypeInfo_BUILDSYSTEM_name, int32(x))
}
func (x *ModuleTypeInfo_BUILDSYSTEM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ModuleTypeInfo_BUILDSYSTEM_value, data, "ModuleTypeInfo_BUILDSYSTEM")
	if err != nil {
		return err
	}
	*x = ModuleTypeInfo_BUILDSYSTEM(value)
	return nil
}
func (ModuleTypeInfo_BUILDSYSTEM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{2, 0}
}

type MetricsBase struct {
	// Timestamp generated when the build starts.
	BuildDateTimestamp *uint64 `protobuf:"varint,1,opt,name=build_date_timestamp,json=buildDateTimestamp" json:"build_date_timestamp,omitempty"`
	// It is usually used to specify the branch name [and release candidate].
	BuildId *string `protobuf:"bytes,2,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	// The platform version codename, eg. P, Q, REL.
	PlatformVersionCodename *string `protobuf:"bytes,3,opt,name=platform_version_codename,json=platformVersionCodename" json:"platform_version_codename,omitempty"`
	// The target product information, eg. aosp_arm.
	TargetProduct *string `protobuf:"bytes,4,opt,name=target_product,json=targetProduct" json:"target_product,omitempty"`
	// The target build variant information, eg. eng.
	TargetBuildVariant *MetricsBase_BUILDVARIANT `protobuf:"varint,5,opt,name=target_build_variant,json=targetBuildVariant,enum=build_metrics.MetricsBase_BUILDVARIANT,def=2" json:"target_build_variant,omitempty"`
	// The target arch information, eg. arm.
	TargetArch *MetricsBase_TARGETARCH `protobuf:"varint,6,opt,name=target_arch,json=targetArch,enum=build_metrics.MetricsBase_TARGETARCH,def=1" json:"target_arch,omitempty"`
	// The target arch variant information, eg. armv7-a-neon.
	TargetArchVariant *string `protobuf:"bytes,7,opt,name=target_arch_variant,json=targetArchVariant" json:"target_arch_variant,omitempty"`
	// The target cpu variant information, eg. generic.
	TargetCpuVariant *string `protobuf:"bytes,8,opt,name=target_cpu_variant,json=targetCpuVariant" json:"target_cpu_variant,omitempty"`
	// The host arch information, eg. x86_64.
	HostArch *MetricsBase_HOSTARCH `protobuf:"varint,9,opt,name=host_arch,json=hostArch,enum=build_metrics.MetricsBase_HOSTARCH,def=1" json:"host_arch,omitempty"`
	// The host 2nd arch information, eg. x86.
	Host_2NdArch *string `protobuf:"bytes,10,opt,name=host_2nd_arch,json=host2ndArch" json:"host_2nd_arch,omitempty"`
	// The host os information, eg. linux.
	HostOs *string `protobuf:"bytes,11,opt,name=host_os,json=hostOs" json:"host_os,omitempty"`
	// The host os extra information, eg. Linux-4.17.0-3rodete2-amd64-x86_64-Debian-GNU.
	HostOsExtra *string `protobuf:"bytes,12,opt,name=host_os_extra,json=hostOsExtra" json:"host_os_extra,omitempty"`
	// The host cross os information, eg. windows.
	HostCrossOs *string `protobuf:"bytes,13,opt,name=host_cross_os,json=hostCrossOs" json:"host_cross_os,omitempty"`
	// The host cross arch information, eg. x86.
	HostCrossArch *string `protobuf:"bytes,14,opt,name=host_cross_arch,json=hostCrossArch" json:"host_cross_arch,omitempty"`
	// The host cross 2nd arch information, eg. x86_64.
	HostCross_2NdArch *string `protobuf:"bytes,15,opt,name=host_cross_2nd_arch,json=hostCross2ndArch" json:"host_cross_2nd_arch,omitempty"`
	// The directory for generated built artifacts installation, eg. out.
	OutDir *string `protobuf:"bytes,16,opt,name=out_dir,json=outDir" json:"out_dir,omitempty"`
	// The metrics for calling various tools (microfactory) before Soong_UI starts.
	SetupTools []*PerfInfo `protobuf:"bytes,17,rep,name=setup_tools,json=setupTools" json:"setup_tools,omitempty"`
	// The metrics for calling Kati by multiple times.
	KatiRuns []*PerfInfo `protobuf:"bytes,18,rep,name=kati_runs,json=katiRuns" json:"kati_runs,omitempty"`
	// The metrics for calling Soong.
	SoongRuns []*PerfInfo `protobuf:"bytes,19,rep,name=soong_runs,json=soongRuns" json:"soong_runs,omitempty"`
	// The metrics for calling Ninja.
	NinjaRuns            []*PerfInfo `protobuf:"bytes,20,rep,name=ninja_runs,json=ninjaRuns" json:"ninja_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetricsBase) Reset()         { *m = MetricsBase{} }
func (m *MetricsBase) String() string { return proto.CompactTextString(m) }
func (*MetricsBase) ProtoMessage()    {}
func (*MetricsBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{0}
}
func (m *MetricsBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsBase.Unmarshal(m, b)
}
func (m *MetricsBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsBase.Marshal(b, m, deterministic)
}
func (dst *MetricsBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsBase.Merge(dst, src)
}
func (m *MetricsBase) XXX_Size() int {
	return xxx_messageInfo_MetricsBase.Size(m)
}
func (m *MetricsBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsBase.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsBase proto.InternalMessageInfo

const Default_MetricsBase_TargetBuildVariant MetricsBase_BUILDVARIANT = MetricsBase_ENG
const Default_MetricsBase_TargetArch MetricsBase_TARGETARCH = MetricsBase_ARM64
const Default_MetricsBase_HostArch MetricsBase_HOSTARCH = MetricsBase_HOST_X86_64

func (m *MetricsBase) GetBuildDateTimestamp() uint64 {
	if m != nil && m.BuildDateTimestamp != nil {
		return *m.BuildDateTimestamp
	}
	return 0
}

func (m *MetricsBase) GetBuildId() string {
	if m != nil && m.BuildId != nil {
		return *m.BuildId
	}
	return ""
}

func (m *MetricsBase) GetPlatformVersionCodename() string {
	if m != nil && m.PlatformVersionCodename != nil {
		return *m.PlatformVersionCodename
	}
	return ""
}

func (m *MetricsBase) GetTargetProduct() string {
	if m != nil && m.TargetProduct != nil {
		return *m.TargetProduct
	}
	return ""
}

func (m *MetricsBase) GetTargetBuildVariant() MetricsBase_BUILDVARIANT {
	if m != nil && m.TargetBuildVariant != nil {
		return *m.TargetBuildVariant
	}
	return Default_MetricsBase_TargetBuildVariant
}

func (m *MetricsBase) GetTargetArch() MetricsBase_TARGETARCH {
	if m != nil && m.TargetArch != nil {
		return *m.TargetArch
	}
	return Default_MetricsBase_TargetArch
}

func (m *MetricsBase) GetTargetArchVariant() string {
	if m != nil && m.TargetArchVariant != nil {
		return *m.TargetArchVariant
	}
	return ""
}

func (m *MetricsBase) GetTargetCpuVariant() string {
	if m != nil && m.TargetCpuVariant != nil {
		return *m.TargetCpuVariant
	}
	return ""
}

func (m *MetricsBase) GetHostArch() MetricsBase_HOSTARCH {
	if m != nil && m.HostArch != nil {
		return *m.HostArch
	}
	return Default_MetricsBase_HostArch
}

func (m *MetricsBase) GetHost_2NdArch() string {
	if m != nil && m.Host_2NdArch != nil {
		return *m.Host_2NdArch
	}
	return ""
}

func (m *MetricsBase) GetHostOs() string {
	if m != nil && m.HostOs != nil {
		return *m.HostOs
	}
	return ""
}

func (m *MetricsBase) GetHostOsExtra() string {
	if m != nil && m.HostOsExtra != nil {
		return *m.HostOsExtra
	}
	return ""
}

func (m *MetricsBase) GetHostCrossOs() string {
	if m != nil && m.HostCrossOs != nil {
		return *m.HostCrossOs
	}
	return ""
}

func (m *MetricsBase) GetHostCrossArch() string {
	if m != nil && m.HostCrossArch != nil {
		return *m.HostCrossArch
	}
	return ""
}

func (m *MetricsBase) GetHostCross_2NdArch() string {
	if m != nil && m.HostCross_2NdArch != nil {
		return *m.HostCross_2NdArch
	}
	return ""
}

func (m *MetricsBase) GetOutDir() string {
	if m != nil && m.OutDir != nil {
		return *m.OutDir
	}
	return ""
}

func (m *MetricsBase) GetSetupTools() []*PerfInfo {
	if m != nil {
		return m.SetupTools
	}
	return nil
}

func (m *MetricsBase) GetKatiRuns() []*PerfInfo {
	if m != nil {
		return m.KatiRuns
	}
	return nil
}

func (m *MetricsBase) GetSoongRuns() []*PerfInfo {
	if m != nil {
		return m.SoongRuns
	}
	return nil
}

func (m *MetricsBase) GetNinjaRuns() []*PerfInfo {
	if m != nil {
		return m.NinjaRuns
	}
	return nil
}

type PerfInfo struct {
	// The description for the phase/action/part while the tool running.
	Desc *string `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	// The name for the running phase/action/part.
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The absolute start time.
	// The number of nanoseconds elapsed since January 1, 1970 UTC.
	StartTime *uint64 `protobuf:"varint,3,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// The real running time.
	// The number of nanoseconds elapsed since start_time.
	RealTime *uint64 `protobuf:"varint,4,opt,name=real_time,json=realTime" json:"real_time,omitempty"`
	// The number of MB for memory use.
	MemoryUse            *uint64  `protobuf:"varint,5,opt,name=memory_use,json=memoryUse" json:"memory_use,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerfInfo) Reset()         { *m = PerfInfo{} }
func (m *PerfInfo) String() string { return proto.CompactTextString(m) }
func (*PerfInfo) ProtoMessage()    {}
func (*PerfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{1}
}
func (m *PerfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerfInfo.Unmarshal(m, b)
}
func (m *PerfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerfInfo.Marshal(b, m, deterministic)
}
func (dst *PerfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerfInfo.Merge(dst, src)
}
func (m *PerfInfo) XXX_Size() int {
	return xxx_messageInfo_PerfInfo.Size(m)
}
func (m *PerfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PerfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PerfInfo proto.InternalMessageInfo

func (m *PerfInfo) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *PerfInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PerfInfo) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *PerfInfo) GetRealTime() uint64 {
	if m != nil && m.RealTime != nil {
		return *m.RealTime
	}
	return 0
}

func (m *PerfInfo) GetMemoryUse() uint64 {
	if m != nil && m.MemoryUse != nil {
		return *m.MemoryUse
	}
	return 0
}

type ModuleTypeInfo struct {
	// The build system, eg. Soong or Make.
	BuildSystem *ModuleTypeInfo_BUILDSYSTEM `protobuf:"varint,1,opt,name=build_system,json=buildSystem,enum=build_metrics.ModuleTypeInfo_BUILDSYSTEM,def=1" json:"build_system,omitempty"`
	// The module type, eg. java_library, cc_binary, and etc.
	ModuleType *string `protobuf:"bytes,2,opt,name=module_type,json=moduleType" json:"module_type,omitempty"`
	// The number of logical modules.
	NumOfModules         *uint32  `protobuf:"varint,3,opt,name=num_of_modules,json=numOfModules" json:"num_of_modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleTypeInfo) Reset()         { *m = ModuleTypeInfo{} }
func (m *ModuleTypeInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleTypeInfo) ProtoMessage()    {}
func (*ModuleTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_e77f238172649e23, []int{2}
}
func (m *ModuleTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleTypeInfo.Unmarshal(m, b)
}
func (m *ModuleTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleTypeInfo.Marshal(b, m, deterministic)
}
func (dst *ModuleTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleTypeInfo.Merge(dst, src)
}
func (m *ModuleTypeInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleTypeInfo.Size(m)
}
func (m *ModuleTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleTypeInfo proto.InternalMessageInfo

const Default_ModuleTypeInfo_BuildSystem ModuleTypeInfo_BUILDSYSTEM = ModuleTypeInfo_MAKE

func (m *ModuleTypeInfo) GetBuildSystem() ModuleTypeInfo_BUILDSYSTEM {
	if m != nil && m.BuildSystem != nil {
		return *m.BuildSystem
	}
	return Default_ModuleTypeInfo_BuildSystem
}

func (m *ModuleTypeInfo) GetModuleType() string {
	if m != nil && m.ModuleType != nil {
		return *m.ModuleType
	}
	return ""
}

func (m *ModuleTypeInfo) GetNumOfModules() uint32 {
	if m != nil && m.NumOfModules != nil {
		return *m.NumOfModules
	}
	return 0
}

func init() {
	proto.RegisterType((*MetricsBase)(nil), "build_metrics.MetricsBase")
	proto.RegisterType((*PerfInfo)(nil), "build_metrics.PerfInfo")
	proto.RegisterType((*ModuleTypeInfo)(nil), "build_metrics.ModuleTypeInfo")
	proto.RegisterEnum("build_metrics.MetricsBase_BUILDVARIANT", MetricsBase_BUILDVARIANT_name, MetricsBase_BUILDVARIANT_value)
	proto.RegisterEnum("build_metrics.MetricsBase_TARGETARCH", MetricsBase_TARGETARCH_name, MetricsBase_TARGETARCH_value)
	proto.RegisterEnum("build_metrics.MetricsBase_HOSTARCH", MetricsBase_HOSTARCH_name, MetricsBase_HOSTARCH_value)
	proto.RegisterEnum("build_metrics.ModuleTypeInfo_BUILDSYSTEM", ModuleTypeInfo_BUILDSYSTEM_name, ModuleTypeInfo_BUILDSYSTEM_value)
}

func init() { proto.RegisterFile("metrics.proto", fileDescriptor_metrics_e77f238172649e23) }

var fileDescriptor_metrics_e77f238172649e23 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xd1, 0x6e, 0xdb, 0x36,
	0x14, 0x8d, 0x62, 0x37, 0xb1, 0xae, 0x6c, 0x47, 0x61, 0x02, 0x44, 0xc5, 0x50, 0x2c, 0xd0, 0xd6,
	0x2d, 0x05, 0x36, 0xa3, 0x30, 0x32, 0x23, 0xc8, 0x9b, 0x9d, 0x18, 0x49, 0xb0, 0x39, 0x2e, 0x68,
	0x27, 0xe8, 0xf6, 0x30, 0x42, 0xb3, 0xe8, 0x46, 0x9b, 0x25, 0x0a, 0x24, 0x55, 0x2c, 0xaf, 0x7b,
	0xdf, 0xb7, 0xed, 0x97, 0x06, 0x5e, 0x5a, 0xb2, 0xda, 0x07, 0xf7, 0x8d, 0x3a, 0xf7, 0x9c, 0xc3,
	0x43, 0xea, 0xea, 0x0a, 0x3a, 0x29, 0xd7, 0x32, 0x59, 0xa8, 0x5e, 0x2e, 0x85, 0x16, 0xa4, 0xf3,
	0x47, 0x91, 0xac, 0x62, 0xb6, 0x06, 0xc3, 0x7f, 0x5c, 0xf0, 0x26, 0x76, 0x3d, 0x8a, 0x14, 0x27,
	0x6f, 0xe1, 0xd8, 0x12, 0xe2, 0x48, 0x73, 0xa6, 0x93, 0x94, 0x2b, 0x1d, 0xa5, 0x79, 0xe0, 0x9c,
	0x3a, 0x67, 0x4d, 0x4a, 0xb0, 0x76, 0x1d, 0x69, 0x3e, 0x2f, 0x2b, 0xe4, 0x25, 0xb4, 0xac, 0x22,
	0x89, 0x83, 0xdd, 0x53, 0xe7, 0xcc, 0xa5, 0xfb, 0xf8, 0x7c, 0x17, 0x93, 0x4b, 0x78, 0x99, 0xaf,
	0x22, 0xbd, 0x14, 0x32, 0x65, 0x1f, 0xb9, 0x54, 0x89, 0xc8, 0xd8, 0x42, 0xc4, 0x3c, 0x8b, 0x52,
	0x1e, 0x34, 0x90, 0x7b, 0x52, 0x12, 0x1e, 0x6d, 0xfd, 0x6a, 0x5d, 0x26, 0xaf, 0xa1, 0xab, 0x23,
	0xf9, 0x81, 0x6b, 0x96, 0x4b, 0x11, 0x17, 0x0b, 0x1d, 0x34, 0x51, 0xd0, 0xb1, 0xe8, 0x3b, 0x0b,
	0x92, 0xdf, 0xe1, 0x78, 0x4d, 0xb3, 0x21, 0x3e, 0x46, 0x32, 0x89, 0x32, 0x1d, 0xbc, 0x38, 0x75,
	0xce, 0xba, 0xfd, 0xef, 0x7b, 0x9f, 0x9c, 0xb6, 0x57, 0x3b, 0x69, 0x6f, 0xf4, 0x70, 0xf7, 0xcb,
	0xf5, 0xe3, 0x90, 0xde, 0x0d, 0xef, 0xe7, 0x97, 0x8d, 0xf1, 0xfd, 0x0d, 0x25, 0xd6, 0x69, 0x64,
	0x24, 0x8f, 0xd6, 0x87, 0x4c, 0xc0, 0x5b, 0xfb, 0x47, 0x72, 0xf1, 0x14, 0xec, 0xa1, 0xed, 0xeb,
	0x2d, 0xb6, 0xf3, 0x21, 0xbd, 0x19, 0xcf, 0x87, 0xf4, 0xea, 0xf6, 0xf2, 0xc5, 0x90, 0x4e, 0x06,
	0xe7, 0x14, 0xac, 0xc1, 0x50, 0x2e, 0x9e, 0x48, 0x0f, 0x8e, 0x6a, 0x76, 0x55, 0xda, 0x7d, 0x3c,
	0xda, 0xe1, 0x86, 0x58, 0x6e, 0xff, 0x03, 0xac, 0x43, 0xb1, 0x45, 0x5e, 0x54, 0xf4, 0x16, 0xd2,
	0x7d, 0x5b, 0xb9, 0xca, 0x8b, 0x4d, 0x58, 0xf7, 0x49, 0xa8, 0x75, 0x54, 0x17, 0xa3, 0x7e, 0xb3,
	0x25, 0xea, 0xed, 0x74, 0x66, 0x83, 0x7a, 0x66, 0xc5, 0xde, 0x5f, 0x0c, 0xd8, 0xe0, 0x9c, 0xb6,
	0x8c, 0x05, 0x86, 0x0d, 0xa1, 0x83, 0x76, 0xfd, 0x2c, 0xb6, 0x96, 0x80, 0xfb, 0x7a, 0x06, 0xec,
	0x67, 0x31, 0x72, 0x4e, 0x60, 0x1f, 0x39, 0x42, 0x05, 0x1e, 0x56, 0xf7, 0xcc, 0xe3, 0x54, 0x55,
	0x62, 0xa1, 0x18, 0xff, 0x5b, 0xcb, 0x28, 0x68, 0x6f, 0xc4, 0x53, 0x35, 0x36, 0x50, 0xc5, 0x59,
	0x48, 0xa1, 0x94, 0xb1, 0xe8, 0x6c, 0x38, 0x57, 0x06, 0x9b, 0x2a, 0xf2, 0x1d, 0x1c, 0xd4, 0x38,
	0x18, 0xa3, 0x6b, 0x1b, 0xa1, 0x62, 0x61, 0x90, 0x1f, 0xe1, 0xa8, 0xc6, 0xab, 0x22, 0x1f, 0xd8,
	0xab, 0xaa, 0xb8, 0xb5, 0xdc, 0xa2, 0xd0, 0x2c, 0x4e, 0x64, 0xe0, 0xdb, 0xdc, 0xa2, 0xd0, 0xd7,
	0x89, 0x24, 0x17, 0xe0, 0x29, 0xae, 0x8b, 0x9c, 0x69, 0x21, 0x56, 0x2a, 0x38, 0x3c, 0x6d, 0x9c,
	0x79, 0xfd, 0x93, 0xcf, 0x6e, 0xf1, 0x1d, 0x97, 0xcb, 0xbb, 0x6c, 0x29, 0x28, 0x20, 0x77, 0x6e,
	0xa8, 0xe4, 0x1c, 0xdc, 0xbf, 0x22, 0x9d, 0x30, 0x59, 0x64, 0x2a, 0x20, 0xdb, 0x75, 0x2d, 0xc3,
	0xa4, 0x45, 0xa6, 0xc8, 0x00, 0x40, 0x09, 0x91, 0x7d, 0xb0, 0xb2, 0xa3, 0xed, 0x32, 0x17, 0xa9,
	0xa5, 0x2e, 0x4b, 0xb2, 0x3f, 0x23, 0xab, 0x3b, 0xfe, 0x82, 0x0e, 0xa9, 0x46, 0x17, 0xbe, 0x85,
	0x76, 0xbd, 0xf3, 0x49, 0x0b, 0x9a, 0x0f, 0xb3, 0x31, 0xf5, 0x77, 0x48, 0x07, 0x5c, 0xb3, 0xba,
	0x1e, 0x8f, 0x1e, 0x6e, 0x7c, 0x87, 0xec, 0x83, 0xf9, 0x28, 0xfc, 0xdd, 0xf0, 0x27, 0x80, 0x4d,
	0x53, 0x1b, 0x78, 0x48, 0x27, 0xfe, 0x0e, 0x71, 0xc1, 0xf6, 0xb7, 0xa5, 0xbe, 0xbf, 0x18, 0xf8,
	0xbb, 0x04, 0x60, 0xcf, 0x76, 0x91, 0xdf, 0x08, 0xdf, 0x40, 0xab, 0x6c, 0x30, 0xd2, 0xb6, 0x6b,
	0xd3, 0x62, 0xfe, 0x0e, 0x39, 0x80, 0x7a, 0xc3, 0xf9, 0x4e, 0xf8, 0xaf, 0x03, 0xad, 0x32, 0x2b,
	0x21, 0xd0, 0x8c, 0xb9, 0x5a, 0xe0, 0xc4, 0x71, 0x29, 0xae, 0x0d, 0x86, 0x33, 0xc3, 0xce, 0x17,
	0x5c, 0x93, 0x57, 0x00, 0x4a, 0x47, 0x52, 0xe3, 0x90, 0xc2, 0x69, 0xd2, 0xa4, 0x2e, 0x22, 0x66,
	0x36, 0x91, 0xaf, 0xc0, 0x95, 0x3c, 0x5a, 0xd9, 0x6a, 0x13, 0xab, 0x2d, 0x03, 0x60, 0xf1, 0x15,
	0x40, 0xca, 0x53, 0x21, 0x9f, 0x59, 0xa1, 0x38, 0xce, 0x8a, 0x26, 0x75, 0x2d, 0xf2, 0xa0, 0x78,
	0xf8, 0x9f, 0x03, 0xdd, 0x89, 0x88, 0x8b, 0x15, 0x9f, 0x3f, 0xe7, 0x1c, 0x53, 0x51, 0x68, 0xdb,
	0xbb, 0x55, 0xcf, 0x4a, 0xf3, 0x14, 0xd3, 0x75, 0xfb, 0x6f, 0x3e, 0xff, 0xba, 0x3e, 0x11, 0xd9,
	0x11, 0x33, 0xfb, 0x75, 0x36, 0x1f, 0x4f, 0x2e, 0x9b, 0x93, 0xe1, 0xcf, 0x63, 0xea, 0x21, 0x7f,
	0x86, 0x1e, 0xe4, 0x6b, 0xf0, 0x52, 0x14, 0x30, 0xfd, 0x9c, 0x97, 0x87, 0x83, 0xb4, 0xf2, 0x20,
	0xdf, 0x42, 0x37, 0x2b, 0x52, 0x26, 0x96, 0xcc, 0x82, 0x0a, 0x8f, 0xd9, 0xa1, 0xed, 0xac, 0x48,
	0xa7, 0x4b, 0xbb, 0x99, 0x0a, 0x43, 0xf0, 0x6a, 0x1b, 0x99, 0xf7, 0x32, 0x9b, 0x4e, 0xef, 0x6f,
	0xfc, 0x1d, 0xf3, 0x6e, 0xcd, 0xae, 0xbe, 0x33, 0x3a, 0xbc, 0x6d, 0xfc, 0x56, 0xfe, 0x08, 0x18,
	0xfe, 0x08, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x34, 0x11, 0x8c, 0x99, 0x18, 0x06, 0x00, 0x00,
}
