// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build/soong/cuj/cuj_proto/cuj.proto

package soong_cuj_metrics_proto

import (
	metrics_proto "build/soong/ui/metrics/metrics_proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CUJ struct {
	Name                 *string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Metrics              *metrics_proto.MetricsBase `protobuf:"bytes,2,opt,name=metrics" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CUJ) Reset()         { *m = CUJ{} }
func (m *CUJ) String() string { return proto.CompactTextString(m) }
func (*CUJ) ProtoMessage()    {}
func (*CUJ) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1da63aec0f8e72c, []int{0}
}

func (m *CUJ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CUJ.Unmarshal(m, b)
}
func (m *CUJ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CUJ.Marshal(b, m, deterministic)
}
func (m *CUJ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CUJ.Merge(m, src)
}
func (m *CUJ) XXX_Size() int {
	return xxx_messageInfo_CUJ.Size(m)
}
func (m *CUJ) XXX_DiscardUnknown() {
	xxx_messageInfo_CUJ.DiscardUnknown(m)
}

var xxx_messageInfo_CUJ proto.InternalMessageInfo

func (m *CUJ) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CUJ) GetMetrics() *metrics_proto.MetricsBase {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CUJSet struct {
	Cujs                 []*CUJ   `protobuf:"bytes,1,rep,name=cujs" json:"cujs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CUJSet) Reset()         { *m = CUJSet{} }
func (m *CUJSet) String() string { return proto.CompactTextString(m) }
func (*CUJSet) ProtoMessage()    {}
func (*CUJSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1da63aec0f8e72c, []int{1}
}

func (m *CUJSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CUJSet.Unmarshal(m, b)
}
func (m *CUJSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CUJSet.Marshal(b, m, deterministic)
}
func (m *CUJSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CUJSet.Merge(m, src)
}
func (m *CUJSet) XXX_Size() int {
	return xxx_messageInfo_CUJSet.Size(m)
}
func (m *CUJSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CUJSet.DiscardUnknown(m)
}

var xxx_messageInfo_CUJSet proto.InternalMessageInfo

func (m *CUJSet) GetCujs() []*CUJ {
	if m != nil {
		return m.Cujs
	}
	return nil
}

func init() {
	proto.RegisterType((*CUJ)(nil), "soong_cuj_metrics.CUJ")
	proto.RegisterType((*CUJSet)(nil), "soong_cuj_metrics.CUJSet")
}

func init() {
	proto.RegisterFile("build/soong/cuj/cuj_proto/cuj.proto", fileDescriptor_f1da63aec0f8e72c)
}

var fileDescriptor_f1da63aec0f8e72c = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2a, 0xcd, 0xcc,
	0x49, 0xd1, 0x2f, 0xce, 0xcf, 0xcf, 0x4b, 0xd7, 0x4f, 0x2e, 0xcd, 0x02, 0xe1, 0xf8, 0x82, 0xa2,
	0xfc, 0x92, 0x7c, 0x10, 0x4b, 0x0f, 0xcc, 0x12, 0x12, 0x04, 0x4b, 0xc7, 0x83, 0xa4, 0x72, 0x53,
	0x4b, 0x8a, 0x32, 0x93, 0x8b, 0xa5, 0x8c, 0x90, 0xf5, 0x95, 0x66, 0xea, 0x43, 0xc5, 0x61, 0x34,
	0xd4, 0x08, 0x28, 0x0f, 0x62, 0x8c, 0x52, 0x28, 0x17, 0xb3, 0x73, 0xa8, 0x97, 0x90, 0x10, 0x17,
	0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x64, 0xc5,
	0xc5, 0x0e, 0x55, 0x2b, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xa0, 0x07, 0xb1, 0x13, 0x6c,
	0x0d, 0xcc, 0x56, 0x3d, 0x5f, 0x08, 0xed, 0x94, 0x58, 0x9c, 0x1a, 0x04, 0xd3, 0xa0, 0x64, 0xc2,
	0xc5, 0xe6, 0x1c, 0xea, 0x15, 0x9c, 0x5a, 0x22, 0xa4, 0xc5, 0xc5, 0x92, 0x5c, 0x9a, 0x55, 0x2c,
	0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa6, 0x87, 0xe1, 0x6c, 0x3d, 0xe7, 0x50, 0xaf, 0x20,
	0xb0, 0x1a, 0x27, 0xc9, 0x28, 0x71, 0x0c, 0x69, 0x88, 0xab, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x68, 0x2c, 0xdf, 0x14, 0x01, 0x00, 0x00,
}
