# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bazel_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61zel_metrics.proto\x12\x19soong_build_bazel_metrics\"k\n\x0c\x42\x61zelMetrics\x12=\n\rphase_timings\x18\x01 \x03(\x0b\x32&.soong_build_bazel_metrics.PhaseTiming\x12\x12\n\x05total\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x08\n\x06_total\"\xa3\x01\n\x0bPhaseTiming\x12\x17\n\nphase_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x64uration_nanos\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\"\n\x15portion_of_build_time\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\r\n\x0b_phase_nameB\x11\n\x0f_duration_nanosB\x18\n\x16_portion_of_build_timeB.Z,android/soong/ui/metrics/bazel_metrics_protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bazel_metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,android/soong/ui/metrics/bazel_metrics_proto'
  _BAZELMETRICS._serialized_start=50
  _BAZELMETRICS._serialized_end=157
  _PHASETIMING._serialized_start=160
  _PHASETIMING._serialized_end=323
# @@protoc_insertion_point(module_scope)
