// Copyright 2022 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package android

import (
	"fmt"
	"strings"

	"github.com/google/blueprint/proptools"
)

func init() {
	ctx := InitRegistrationContext
	ctx.RegisterParallelSingletonModuleType("buildinfo_prop", buildinfoPropFactory)
}

type buildinfoPropProperties struct {
	// Whether this module is directly installable to one of the partitions. Default: true.
	Installable *bool
}

type buildinfoPropModule struct {
	SingletonModuleBase

	properties buildinfoPropProperties

	outputFilePath OutputPath
	installPath    InstallPath
}

var _ OutputFileProducer = (*buildinfoPropModule)(nil)

func (p *buildinfoPropModule) installable() bool {
	return proptools.BoolDefault(p.properties.Installable, true)
}

// OutputFileProducer
func (p *buildinfoPropModule) OutputFiles(tag string) (Paths, error) {
	if tag != "" {
		return nil, fmt.Errorf("unsupported tag %q", tag)
	}
	return Paths{p.outputFilePath}, nil
}

func getBuildVariant(ctx PathContext) string {
	if ctx.Config().Eng() {
		return "eng"
	} else if ctx.Config().Debuggable() {
		return "userdebug"
	} else {
		return "user"
	}
}

func getBuildKeys(ctx PathContext) string {
	_, keyPath := ctx.Config().DefaultAppCertificate(ctx)
	if strings.TrimSuffix(keyPath.String(), keyPath.Ext()) == "build/make/target/product/security/testkey" {
		return "test-keys"
	} else {
		return "dev-keys"
	}
}

func getVersionTags(ctx PathContext, buildKeys string) []string {
	var versionTags []string
	if ctx.Config().BuildType() == "debug" {
		versionTags = append(versionTags, "debug")
	}
	versionTags = append(versionTags, buildKeys)
	return versionTags
}

func (p *buildinfoPropModule) GenerateAndroidBuildActions(ctx ModuleContext) {
	p.outputFilePath = PathForModuleOut(ctx, p.Name()).OutputPath
	if !ctx.Config().KatiEnabled() {
		WriteFileRule(ctx, p.outputFilePath, "# no buildinfo.prop if kati is disabled")
		return
	}

	rule := NewRuleBuilder(pctx, ctx)
	rule.Command().Text("truncate").FlagWithArg("-s", "0").Output(p.outputFilePath)

	config := ctx.Config()
	buildVariant := getBuildVariant(ctx)
	buildKeys := getBuildKeys(ctx)
	versionTags := getVersionTags(ctx, buildKeys)

	// writeString(str): write str as-is (including whitespaces and newlines) to output.
	writeString := func(str string) {
		rule.Command().Text("echo").
			Flag("-n").
			Flag("-e").
			Text(proptools.ShellEscapeIncludingSpaces(strings.Replace(str, "\n", "\\n", -1))).
			FlagWithArg(">> ", p.outputFilePath.String())
	}

	const (
		excludeFromDeps = false
		addToDeps       = true
	)

	// writeFileContents(path, deps): write stripped contents in path to output. Add path to deps if deps == addToDeps.
	writeFileContents := func(path Path, deps bool) {
		cmd := rule.Command().Text("echo").
			Flag("-n").
			Text("$(cat").
			Text(proptools.ShellEscapeIncludingSpaces(path.String())).
			Text(")").
			FlagWithArg(">> ", p.outputFilePath.String())

		if deps {
			cmd.Implicit(path)
		}
	}

	// writePropFromFile(path, deps): write "key={contents in path}" to output.  Add path to deps if deps == addToDeps.
	writePropFromFile := func(key string, path Path, deps bool) {
		if strings.Contains(key, "=") {
			panic(fmt.Errorf("wrong property key %q: key must not contain '='", key))
		}
		writeString(key + "=")
		writeFileContents(path, deps)
		writeString("\n")
	}

	// writeProp(path): write "key=value" to output.
	writeProp := func(key, value string) {
		if strings.Contains(key, "=") {
			panic(fmt.Errorf("wrong property key %q: key must not contain '='", key))
		}
		writeString(key + "=" + value + "\n")
	}

	// write build desc ({DEVICE_PRODUCT}-{BUILD_VARIANT} {PLATFORM_VERSION_NAME} {BUILD_ID} {BUILD_NUMBER} {BUILD_VERSION_TAGS})
	// which is human readable strings that describe this build. This has the same info as the build fingerprint.
	// e.g. "aosp_cf_x86_64_phone-userdebug VanillaIceCream MAIN eng.20240319.143939 test-keys"
	writeBuildDesc := func() {
		writeString(config.DeviceProduct() + "-" + buildVariant + " " + config.PlatformVersionName() + " " + config.BuildId() + " ")
		writeFileContents(config.BuildNumberFile(ctx), excludeFromDeps)
		writeString(" " + strings.Join(versionTags, ","))
	}

	writeString("# begin build properties\n")
	writeString("# autogenerated by build/soong/android/buildinfo_prop.go\n")

	if config.BoardUseVbmetaDigestInFingerprint() {
		writeProp("ro.build.legacy.id", config.BuildId())
	} else {
		writeProp("ro.build.id?", config.BuildId())
	}

	// ro.build.display.id is shown under Settings -> About Phone
	writeString("ro.build.display.id?=")
	if buildVariant == "user" {
		// User builds should show:
		// release build number or branch.buld_number non-release builds

		// Dev. branches should have DISPLAY_BUILD_NUMBER set
		if config.DisplayBuildNumber() {
			// {BUILD_ID} {BUILD_NUMBER} {BUILD_KEYS}
			writeString(config.BuildId() + ".")
			writeFileContents(config.BuildNumberFile(ctx), excludeFromDeps)
			writeString(" " + buildKeys + "\n")
		} else {
			// {BUILD_ID} {BUILD_KEYS}
			writeString(config.BuildId() + " " + buildKeys + "\n")
		}
	} else {
		// Non-user builds should show detailed build information (See build desc above)
		writeBuildDesc()
		writeString("\n")
	}

	writePropFromFile("ro.build.version.incremental", config.BuildNumberFile(ctx), excludeFromDeps)
	writeProp("ro.build.version.sdk", config.PlatformSdkVersion().String())
	writeProp("ro.build.version.preview_sdk", config.PlatformPreviewSdkVersion())
	writePropFromFile("ro.build.version.preview_sdk_fingerprint", ApiFingerprintPath(ctx), addToDeps)
	writeProp("ro.build.version.codename", config.PlatformSdkCodename())
	writeProp("ro.build.version.all_codenames", strings.Join(config.PlatformVersionActiveCodenames(), ","))
	writeProp("ro.build.version.known_codenames", config.PlatformVersionKnownCodenames())
	writeProp("ro.build.version.release", config.PlatformVersionLastStable())
	writeProp("ro.build.version.release_or_codename", config.PlatformVersionName())
	writeProp("ro.build.version.release_or_preview_display", config.PlatformDisplayVersionName())
	writeProp("ro.build.version.security_patch", config.PlatformSecurityPatch())
	writeProp("ro.build.version.base_os", config.PlatformBaseOS())
	writeProp("ro.build.version.min_supported_target_sdk", config.PlatformMinSupportedTargetSdkVersion())

	datetimeFilePath := ctx.Config().Getenv("BUILD_DATETIME_FILE")
	writeString("ro.build.date=")
	rule.Command().Text("date").
		Flag("-d").
		Text("@$(cat ").
		Text(proptools.ShellEscapeIncludingSpaces(datetimeFilePath)).
		Text(")").
		FlagWithArg(">> ", p.outputFilePath.String())

	writeString("ro.build.date.utc=")
	rule.Command().Text("date").
		Flag("-d").
		Text("@$(cat ").
		Text(proptools.ShellEscapeIncludingSpaces(datetimeFilePath)).
		Text(")").
		Flag("+%s").
		FlagWithArg(">> ", p.outputFilePath.String())

	writeProp("ro.build.type", buildVariant)
	writeProp("ro.build.user", ctx.Config().Getenv("BUILD_USERNAME"))
	writePropFromFile("ro.build.host", config.BuildHostnameFile(ctx), addToDeps)

	// TODO: Remove any tag-related optional property declarations once the goals
	// from go/arc-android-sigprop-changes have been achieved.
	writeProp("ro.build.tags?", strings.Join(versionTags, ","))

	// ro.build.flavor are used only by the test harness to distinguish builds.
	// Only add _asan for a sanitized build if it isn't already a part of the
	// flavor (via a dedicated lunch config for example).
	buildFlavor := config.DeviceProduct() + "-" + buildVariant
	if InList("address", config.SanitizeDevice()) && !strings.Contains(buildFlavor, "_asan") {
		buildFlavor += "_asan"
	}
	writeProp("ro.build.flavor", buildFlavor)

	writeString("# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n")
	writeString("# use ro.product.cpu.abilist instead.\n")
	writeProp("ro.product.cpu.abi", config.DeviceAbi()[0])
	if len(config.DeviceAbi()) > 1 {
		writeProp("ro.product.cpu.abi2", config.DeviceAbi()[1])
	}

	if len(config.ProductLocales()) > 0 {
		writeProp("ro.product.locale", config.ProductLocales()[0])
	}

	writeProp("ro.wifi.channels", strings.Join(config.ProductDefaultWifiChannels(), " "))

	writeString("# ro.build.product is obsolete; use ro.product.device\n")
	writeProp("ro.build.product", config.DeviceName())

	writeString("# Do not try to parse description or thumbprint\n")
	writeString("ro.build.description?=")
	writeBuildDesc()
	writeString("\n")

	knownOemProperties := []string{
		"ro.product.brand",
		"ro.product.name",
		"ro.product.device",
	}

	for _, knownProp := range knownOemProperties {
		if InList(knownProp, config.OemProperties()) {
			writePropFromFile("ro.build.thumbprint", config.BuildThumbprintFile(ctx), excludeFromDeps)
			break
		}
	}

	writeString("# end build properties\n")

	rule.Build(ctx.ModuleName(), "generating buildinfo props")

	if !p.installable() {
		p.SkipInstall()
	}

	p.installPath = PathForModuleInstall(ctx)
	ctx.InstallFile(p.installPath, p.Name(), p.outputFilePath)
}

func (f *buildinfoPropModule) GenerateSingletonBuildActions(ctx SingletonContext) {
	// does nothing; buildinfo_prop is a singeton because two buildinfo modules don't make sense.
}

func (p *buildinfoPropModule) AndroidMkEntries() []AndroidMkEntries {
	return []AndroidMkEntries{AndroidMkEntries{
		Class:      "ETC",
		OutputFile: OptionalPathForPath(p.outputFilePath),
		ExtraEntries: []AndroidMkExtraEntriesFunc{
			func(ctx AndroidMkExtraEntriesContext, entries *AndroidMkEntries) {
				entries.SetString("LOCAL_MODULE_PATH", p.installPath.String())
				entries.SetString("LOCAL_INSTALLED_MODULE_STEM", p.outputFilePath.Base())
				entries.SetBoolIfTrue("LOCAL_UNINSTALLABLE_MODULE", !p.installable())
			},
		},
	}}
}

// buildinfo_prop module generates a build.prop file, which contains a set of common
// system/build.prop properties, such as ro.build.version.*.  Not all properties are implemented;
// currently this module is only for microdroid.
func buildinfoPropFactory() SingletonModule {
	module := &buildinfoPropModule{}
	module.AddProperties(&module.properties)
	InitAndroidModule(module)
	return module
}
