// Copyright 2017 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cc

import (
	"android/soong/android"
)

type kernelHeadersDecorator struct {
	*libraryDecorator
}

func (stub *kernelHeadersDecorator) link(ctx ModuleContext, flags Flags, deps PathDeps, objs Objects) android.Path {
	if ctx.Device() {
		f := &stub.libraryDecorator.flagExporter
		for _, dir := range ctx.DeviceConfig().DeviceKernelHeaderDirs() {
			f.flags = append(f.flags, "-isystem "+dir)
		}
	}
	return stub.libraryDecorator.linkStatic(ctx, flags, deps, objs)
}

// kernel_headers is the equivalent of cc_header_library that retrieves the
// list of directories defined in TARGET_BOARD_KERNEL_HEADERS and
// TARGET_PRODUCT_KERNEL_HEADERS make variables that contains the kernel header
// files in a makefile andare  included during compilation of a module.
// See the following explanation of each makefile variable:
//
//     *  TARGET_DEVICE_KERNEL_HEADERS: automatically created for the current
//        device being built. It is set as $(TARGET_DEVICE_DIR)/kernel-headers,
//        e.g. device/samsung/tuna/kernel-headers. This directory is not
//        explicitly set by anyone, the build system always adds this subdir.
//
//     * TARGET_BOARD_KERNEL_HEADERS: specified by the BoardConfig.mk file
//        to allow other directories to be included. This is useful if there's
//        some common place where a few headers are being kept for a group
//        of devices. For example, device/<vendor>/common/kernel-headers could
//        contain some headers for several of <vendor>'s devices.
//
//     * TARGET_PRODUCT_KERNEL_HEADERS: generated by the product inheritance
//        graph. This allows architecture products to provide headers for the
//        devices using that architecture. For example,
//        hardware/ti/omap4xxx/omap4.mk will specify
//        PRODUCT_VENDOR_KERNEL_HEADERS variable that specify where the omap4
//        specific headers are, e.g. hardware/ti/omap4xxx/kernel-headers.
//        The build system then combines all the values specified by all the
//        PRODUCT_VENDOR_KERNEL_HEADERS directives in the product inheritance
//        tree and then exports a TARGET_PRODUCT_KERNEL_HEADERS variable.
func kernelHeadersFactory() android.Module {
	module, library := NewLibrary(android.HostAndDeviceSupported)
	library.HeaderOnly()

	stub := &kernelHeadersDecorator{
		libraryDecorator: library,
	}

	module.linker = stub

	return module.Init()
}

func init() {
	android.RegisterModuleType("kernel_headers", kernelHeadersFactory)
}
