// Copyright 2015 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package common

import (
	"github.com/google/blueprint"
)

var (
	pctx = blueprint.NewPackageContext("android/soong/common")

	cpPreserveSymlinks = pctx.VariableConfigMethod("cpPreserveSymlinks",
		Config.CpPreserveSymlinksFlags)

	// A phony rule that is not the built-in Ninja phony rule.  The built-in
	// phony rule has special behavior that is sometimes not desired.  See the
	// Ninja docs for more details.
	Phony = pctx.StaticRule("Phony",
		blueprint.RuleParams{
			Command:     "# phony $out",
			Description: "phony $out",
		})

	// GeneratedFile is a rule for indicating that a given file was generated
	// while running soong.  This allows the file to be cleaned up if it ever
	// stops being generated by soong.
	GeneratedFile = pctx.StaticRule("GeneratedFile",
		blueprint.RuleParams{
			Command:     "# generated $out",
			Description: "generated $out",
			Generator:   true,
		})

	// A copy rule.
	Cp = pctx.StaticRule("Cp",
		blueprint.RuleParams{
			Command:     "cp $cpPreserveSymlinks $cpFlags $in $out",
			Description: "cp $out",
		},
		"cpFlags")

	// A symlink rule.
	Symlink = pctx.StaticRule("Symlink",
		blueprint.RuleParams{
			Command:     "ln -f -s $fromPath $out",
			Description: "symlink $out",
		},
		"fromPath")

	ProductOut = pctx.VariableFunc("ProductOut", func(c interface{}) (string, error) {
		return c.(Config).DeviceOut(), nil
	})
	LibDir = pctx.VariableFunc("LibDir", func(c interface{}) (string, error) {
		if true /* && target_is_64_bit */ {
			return "lib64", nil
		} else {
			return "lib", nil
		}
	})

	TargetRootOut = pctx.StaticVariable("TargetRootOut", "${ProductOut}/root")
	TargetRootBin = pctx.StaticVariable("TargetRootBin", "${TargetRootOut}/bin")
	TargetRootSbin = pctx.StaticVariable("TargetRootSbin", "${TargetRootOut}/sbin")
	TargetRootEtc = pctx.StaticVariable("TargetRootEtc", "${TargetRootOut}/etc")
	TargetRootUsr = pctx.StaticVariable("TargetRootUsr", "${TargetRootOut}/usr")

	SystemOut = pctx.StaticVariable("SystemOut", "${ProductOut}/system")
	SystemBin = pctx.StaticVariable("SystemBin", "${SystemOut}/bin")
	SystemXbin = pctx.StaticVariable("SystemXbin", "${SystemOut}/xbin")
	SystemLib = pctx.StaticVariable("SystemLib", "$SystemOut}/${LibDir}")
	SystemJavaLib = pctx.StaticVariable("SystemJavaLib", "${SystemOut}/framework")
	SystemApp = pctx.StaticVariable("SystemApp", "${SystemOut}/app")
	SystemPrivApp = pctx.StaticVariable("SystemPrivApp", "${SystemOut}/priv-app")
	SystemKeyLayout = pctx.StaticVariable("SystemKeyLayout", "${SystemOut}/usr/keylayout")
	SystemKeyChars = pctx.StaticVariable("SystemKeyChars", "${SystemOut}/usr/keychars")
	SystemEtc = pctx.StaticVariable("SystemEtc", "${SystemOut}/etc")
	SystemFake = pctx.StaticVariable("SystemFake", "${ProductOut}/fake_packages")

	DataOut = pctx.StaticVariable("DataOut", "${ProductOut}/data")
	DataBin = pctx.StaticVariable("DataBin", "${SystemBin}")
	DataLib = pctx.StaticVariable("DataLib", "${SystemLib}")
	DataJavaLib = pctx.StaticVariable("DataJavaLib", "${DataOut}/framework")
	DataApp = pctx.StaticVariable("DataApp", "${DataOut}/app")
	DataKeyLayout = pctx.StaticVariable("DataKeyLayout", "${SystemKeyLayout}")
	DataKeyChars = pctx.StaticVariable("DataKeyChars", "${SystemKeyChars}")
	DataEtc = pctx.StaticVariable("DataEtc", "${SystemEtc}")
	DataFake = pctx.StaticVariable("DataFake", "${DataOut}/fake_packages")

	CacheOut = pctx.StaticVariable("CacheOut", "${ProductOut}/cache")

	VendorOut = pctx.StaticVariable("VendorOut", "${ProductOut}/vendor")
	VendorBin = pctx.StaticVariable("VendorBin", "${VendorOut}/bin")
	VendorXbin = pctx.StaticVariable("VendorXbin", "${VendorOut}/xbin")
	VendorLib = pctx.StaticVariable("VendorLib", "${VendorOut}/${LibDir}")
	VendorJavaLib = pctx.StaticVariable("VendorJavaLib", "${VendorOut}/framework")
	VendorApp = pctx.StaticVariable("VendorApp", "${VendorOut}/app")
	VendorEtc = pctx.StaticVariable("VendorEtc", "${VendorOut}/etc")

	OemOut = pctx.StaticVariable("OemOut", "${ProductOut}/vendor")
	OemBin = pctx.StaticVariable("OemBin", "${OemOut}/bin")
	OemLib = pctx.StaticVariable("OemLib", "${OemOut}/${LibDir}")
	OemApp = pctx.StaticVariable("OemApp", "${OemOut}/app")
	OemEtc = pctx.StaticVariable("OemEtc", "${OemOut}/etc")

	RecoveryOut = pctx.StaticVariable("RecoveryOut", "${ProductOut}/recovery")
	RecoveryRoot = pctx.StaticVariable("RecoveryRoot", "${RecoveryOut}/root")

	SysloaderOut = pctx.StaticVariable("SysloaderOut", "${ProductOut}/sysloader")
	SysloaderRoot = pctx.StaticVariable("SysloaderRoot", "${SysloaderOut}/root")
	SysloaderSystem = pctx.StaticVariable("SysloaderSystem", "${SysloaderRoot}/system")

	InstallerOut = pctx.StaticVariable("InstallerOut", "${ProductOut}/installer")
	InstallerData = pctx.StaticVariable("InstallerData", "${InstallerOut}/data")
	InstallerRoot = pctx.StaticVariable("InstallerRoot", "${InstallerOut}/root")
	InstallerSystem = pctx.StaticVariable("InstallerSystem", "${InstallerRoot}/system")

	HostOut = pctx.VariableFunc("HostOut", func(c interface{}) (string, error) {
		return c.(Config).HostOut(), nil
	})
	HostBin = pctx.StaticVariable("HostBin", "${HostOut}/bin")
	HostLib = pctx.StaticVariable("HostLib", "${HostOut}/lib64")
	HostJavaLib = pctx.StaticVariable("HostJavaLib", "${HostOut}/framework")
	HostSdkAddon = pctx.StaticVariable("HostSdkAddon", "${HostOut}/sdk_addon")
	HostFake = pctx.StaticVariable("HostFake", "${HostOut}/fake_packages")
)
