// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sbox.proto

package sbox_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A set of commands to run in a sandbox.
type Manifest struct {
	// A list of commands to run in the sandbox.
	Commands []*Command `protobuf:"bytes,1,rep,name=commands" json:"commands,omitempty"`
	// If set, GCC-style dependency files from any command that references __SBOX_DEPFILE__ will be
	// merged into the given output file relative to the $PWD when sbox was started.
	Depfile              *string  `protobuf:"bytes,2,opt,name=depfile" json:"depfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
func (*Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0425bf0de86ed1, []int{0}
}

func (m *Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manifest.Unmarshal(m, b)
}
func (m *Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manifest.Marshal(b, m, deterministic)
}
func (m *Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manifest.Merge(m, src)
}
func (m *Manifest) XXX_Size() int {
	return xxx_messageInfo_Manifest.Size(m)
}
func (m *Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_Manifest proto.InternalMessageInfo

func (m *Manifest) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *Manifest) GetDepfile() string {
	if m != nil && m.Depfile != nil {
		return *m.Depfile
	}
	return ""
}

// SandboxManifest describes a command to run in the sandbox.
type Command struct {
	// A list of copy rules to run before the sandboxed command.  The from field is relative to the
	// $PWD when sbox was run, the to field is relative to the top of the temporary sandbox directory.
	CopyBefore []*Copy `protobuf:"bytes,1,rep,name=copy_before,json=copyBefore" json:"copy_before,omitempty"`
	// If true, change the working directory to the top of the temporary sandbox directory before
	// running the command.  If false, leave the working directory where it was when sbox was started.
	Chdir *bool `protobuf:"varint,2,opt,name=chdir" json:"chdir,omitempty"`
	// The command to run.
	Command *string `protobuf:"bytes,3,req,name=command" json:"command,omitempty"`
	// A list of copy rules to run after the sandboxed command.  The from field is relative to the
	// top of the temporary sandbox directory, the to field is relative to the $PWD when sbox was run.
	CopyAfter []*Copy `protobuf:"bytes,4,rep,name=copy_after,json=copyAfter" json:"copy_after,omitempty"`
	// An optional hash of the input files to ensure the textproto files and the sbox rule reruns
	// when the lists of inputs changes, even if the inputs are not on the command line.
	InputHash            *string  `protobuf:"bytes,5,opt,name=input_hash,json=inputHash" json:"input_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0425bf0de86ed1, []int{1}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCopyBefore() []*Copy {
	if m != nil {
		return m.CopyBefore
	}
	return nil
}

func (m *Command) GetChdir() bool {
	if m != nil && m.Chdir != nil {
		return *m.Chdir
	}
	return false
}

func (m *Command) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *Command) GetCopyAfter() []*Copy {
	if m != nil {
		return m.CopyAfter
	}
	return nil
}

func (m *Command) GetInputHash() string {
	if m != nil && m.InputHash != nil {
		return *m.InputHash
	}
	return ""
}

// Copy describes a from-to pair of files to copy.  The paths may be relative, the root that they
// are relative to is specific to the context the Copy is used in and will be different for
// from and to.
type Copy struct {
	From                 *string  `protobuf:"bytes,1,req,name=from" json:"from,omitempty"`
	To                   *string  `protobuf:"bytes,2,req,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Copy) Reset()         { *m = Copy{} }
func (m *Copy) String() string { return proto.CompactTextString(m) }
func (*Copy) ProtoMessage()    {}
func (*Copy) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0425bf0de86ed1, []int{2}
}

func (m *Copy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Copy.Unmarshal(m, b)
}
func (m *Copy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Copy.Marshal(b, m, deterministic)
}
func (m *Copy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Copy.Merge(m, src)
}
func (m *Copy) XXX_Size() int {
	return xxx_messageInfo_Copy.Size(m)
}
func (m *Copy) XXX_DiscardUnknown() {
	xxx_messageInfo_Copy.DiscardUnknown(m)
}

var xxx_messageInfo_Copy proto.InternalMessageInfo

func (m *Copy) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *Copy) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func init() {
	proto.RegisterType((*Manifest)(nil), "sbox.Manifest")
	proto.RegisterType((*Command)(nil), "sbox.Command")
	proto.RegisterType((*Copy)(nil), "sbox.Copy")
}

func init() {
	proto.RegisterFile("sbox.proto", fileDescriptor_9d0425bf0de86ed1)
}

var fileDescriptor_9d0425bf0de86ed1 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x37, 0x55, 0x93, 0x2b, 0x30, 0x9c, 0x18, 0xbc, 0x20, 0x45, 0x99, 0x5a, 0x90,
	0x3a, 0xf0, 0x0f, 0x28, 0x0b, 0x0b, 0x42, 0xca, 0xc8, 0x12, 0xb9, 0x89, 0xad, 0x44, 0x22, 0x39,
	0xcb, 0x36, 0x12, 0xfd, 0x57, 0xfc, 0x44, 0xe4, 0xab, 0xc3, 0xd2, 0xed, 0xee, 0x7d, 0x7e, 0xef,
	0x59, 0x07, 0xe0, 0x4f, 0xf4, 0x73, 0xb0, 0x8e, 0x02, 0x61, 0x1e, 0xe7, 0xfa, 0x03, 0x8a, 0x77,
	0x35, 0x8f, 0x46, 0xfb, 0x80, 0x7b, 0x28, 0x3a, 0x9a, 0x26, 0x35, 0xf7, 0x5e, 0x66, 0xd5, 0x6a,
	0xb7, 0x7d, 0xbe, 0x3d, 0xb0, 0xe1, 0xf5, 0xa2, 0x36, 0xff, 0x18, 0x25, 0x6c, 0x7a, 0x6d, 0xcd,
	0xf8, 0xa5, 0xa5, 0xa8, 0xb2, 0x5d, 0xd9, 0x2c, 0x6b, 0xfd, 0x9b, 0xc1, 0x26, 0xbd, 0xc7, 0x27,
	0xd8, 0x76, 0x64, 0xcf, 0xed, 0x49, 0x1b, 0x72, 0x3a, 0x65, 0xc2, 0x92, 0x69, 0xcf, 0x0d, 0x44,
	0x7c, 0x64, 0x8a, 0xf7, 0xb0, 0xee, 0x86, 0x7e, 0x74, 0x1c, 0x58, 0x34, 0x97, 0x25, 0x16, 0xa5,
	0x52, 0xb9, 0xaa, 0x44, 0x2c, 0x4a, 0x2b, 0xee, 0x81, 0xdd, 0xad, 0x32, 0x41, 0x3b, 0x99, 0x5f,
	0x65, 0x97, 0x91, 0xbe, 0x44, 0x88, 0x0f, 0x00, 0xe3, 0x6c, 0xbf, 0x43, 0x3b, 0x28, 0x3f, 0xc8,
	0x35, 0x7f, 0xb8, 0x64, 0xe5, 0x4d, 0xf9, 0xa1, 0x7e, 0x84, 0x3c, 0x3a, 0x10, 0x21, 0x37, 0x8e,
	0x26, 0x99, 0x71, 0x11, 0xcf, 0x78, 0x07, 0x22, 0x90, 0x14, 0xac, 0x88, 0x40, 0xc7, 0x9b, 0x4f,
	0xbe, 0x61, 0xcb, 0x37, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xdd, 0x84, 0xbb, 0x50, 0x01,
	0x00, 0x00,
}
