// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upload.proto

package soong_metrics_upload_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Upload struct {
	// The timestamp in milliseconds that the build was created.
	CreationTimestamp *uint64 `protobuf:"varint,1,opt,name=creation_timestamp,json=creationTimestamp" json:"creation_timestamp,omitempty"`
	// The timestamp in milliseconds when the build was completed.
	CompletionTimestamp *uint64 `protobuf:"varint,2,opt,name=completion_timestamp,json=completionTimestamp" json:"completion_timestamp,omitempty"`
	// The branch name.
	BranchName *string `protobuf:"bytes,3,opt,name=branch_name,json=branchName" json:"branch_name,omitempty"`
	// The target name.
	TargetName *string `protobuf:"bytes,4,opt,name=target_name,json=targetName" json:"target_name,omitempty"`
	// A list of metrics filepaths to upload.
	MetricsFiles         []string `protobuf:"bytes,5,rep,name=metrics_files,json=metricsFiles" json:"metrics_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Upload) Reset()         { *m = Upload{} }
func (m *Upload) String() string { return proto.CompactTextString(m) }
func (*Upload) ProtoMessage()    {}
func (*Upload) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

func (m *Upload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upload.Unmarshal(m, b)
}
func (m *Upload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upload.Marshal(b, m, deterministic)
}
func (m *Upload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upload.Merge(m, src)
}
func (m *Upload) XXX_Size() int {
	return xxx_messageInfo_Upload.Size(m)
}
func (m *Upload) XXX_DiscardUnknown() {
	xxx_messageInfo_Upload.DiscardUnknown(m)
}

var xxx_messageInfo_Upload proto.InternalMessageInfo

func (m *Upload) GetCreationTimestamp() uint64 {
	if m != nil && m.CreationTimestamp != nil {
		return *m.CreationTimestamp
	}
	return 0
}

func (m *Upload) GetCompletionTimestamp() uint64 {
	if m != nil && m.CompletionTimestamp != nil {
		return *m.CompletionTimestamp
	}
	return 0
}

func (m *Upload) GetBranchName() string {
	if m != nil && m.BranchName != nil {
		return *m.BranchName
	}
	return ""
}

func (m *Upload) GetTargetName() string {
	if m != nil && m.TargetName != nil {
		return *m.TargetName
	}
	return ""
}

func (m *Upload) GetMetricsFiles() []string {
	if m != nil {
		return m.MetricsFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Upload)(nil), "soong_metrics_upload.Upload")
}

func init() {
	proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5)
}

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2d, 0xc8, 0xc9,
	0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x29, 0xce, 0xcf, 0xcf, 0x4b, 0x8f,
	0xcf, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x2e, 0x8e, 0x87, 0xc8, 0x29, 0x5d, 0x64, 0xe4, 0x62, 0x0b,
	0x05, 0x33, 0x85, 0x74, 0xb9, 0x84, 0x92, 0x8b, 0x52, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0xe2, 0x4b,
	0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x04,
	0x61, 0x32, 0x21, 0x30, 0x09, 0x21, 0x43, 0x2e, 0x91, 0xe4, 0xfc, 0xdc, 0x82, 0x9c, 0x54, 0x34,
	0x0d, 0x4c, 0x60, 0x0d, 0xc2, 0x08, 0x39, 0x84, 0x16, 0x79, 0x2e, 0xee, 0xa4, 0xa2, 0xc4, 0xbc,
	0xe4, 0x8c, 0xf8, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x2e, 0x88,
	0x90, 0x5f, 0x62, 0x6e, 0x2a, 0x48, 0x41, 0x49, 0x62, 0x51, 0x7a, 0x6a, 0x09, 0x44, 0x01, 0x0b,
	0x44, 0x01, 0x44, 0x08, 0xac, 0x40, 0x99, 0x8b, 0x17, 0xe6, 0x81, 0xb4, 0xcc, 0x9c, 0xd4, 0x62,
	0x09, 0x56, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x1e, 0xa8, 0xa0, 0x1b, 0x48, 0xcc, 0x49, 0x26, 0x4a,
	0x0a, 0x9b, 0x5f, 0xe3, 0xc1, 0xe1, 0x00, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x8c, 0x81, 0xc9,
	0x16, 0x01, 0x00, 0x00,
}
