//
// Copyright (C) 2022 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.9.1
// source: provenance_metadata.proto

package provenance_metadata_proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provenance metadata of artifacts.
type ProvenanceMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the module/target that creates the artifact.
	// It is either a Soong module name or Bazel target label.
	ModuleName string `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	// The path to the prebuilt artifacts, which is relative to the source tree
	// directory. For example, “prebuilts/runtime/mainline/i18n/apex/com.android.i18n-arm.apex”.
	ArtifactPath string `protobuf:"bytes,2,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	// The SHA256 hash of the artifact.
	ArtifactSha256 string `protobuf:"bytes,3,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`
	// The install path of the artifact in filesystem images.
	// This is the absolute path of the artifact on the device.
	ArtifactInstallPath string `protobuf:"bytes,4,opt,name=artifact_install_path,json=artifactInstallPath,proto3" json:"artifact_install_path,omitempty"`
	// Path of the attestation file of a prebuilt artifact, which is relative to
	// the source tree directory. This is for prebuilt artifacts which have
	// corresponding attestation files checked in the source tree.
	AttestationPath string `protobuf:"bytes,5,opt,name=attestation_path,json=attestationPath,proto3" json:"attestation_path,omitempty"`
}

func (x *ProvenanceMetaData) Reset() {
	*x = ProvenanceMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provenance_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvenanceMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvenanceMetaData) ProtoMessage() {}

func (x *ProvenanceMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvenanceMetaData.ProtoReflect.Descriptor instead.
func (*ProvenanceMetaData) Descriptor() ([]byte, []int) {
	return file_provenance_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ProvenanceMetaData) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ProvenanceMetaData) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ProvenanceMetaData) GetArtifactSha256() string {
	if x != nil {
		return x.ArtifactSha256
	}
	return ""
}

func (x *ProvenanceMetaData) GetArtifactInstallPath() string {
	if x != nil {
		return x.ArtifactInstallPath
	}
	return ""
}

func (x *ProvenanceMetaData) GetAttestationPath() string {
	if x != nil {
		return x.AttestationPath
	}
	return ""
}

type ProvenanceMetaDataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata []*ProvenanceMetaData `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ProvenanceMetaDataList) Reset() {
	*x = ProvenanceMetaDataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provenance_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvenanceMetaDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvenanceMetaDataList) ProtoMessage() {}

func (x *ProvenanceMetaDataList) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvenanceMetaDataList.ProtoReflect.Descriptor instead.
func (*ProvenanceMetaDataList) Descriptor() ([]byte, []int) {
	return file_provenance_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ProvenanceMetaDataList) GetMetadata() []*ProvenanceMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_provenance_metadata_proto protoreflect.FileDescriptor

var file_provenance_metadata_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x76, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f,
	0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x32, 0x0a, 0x15,
	0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x29, 0x0a, 0x10, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x22, 0x63, 0x0a, 0x16, 0x50,
	0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x2e, 0x5a, 0x2c, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x73, 0x6f, 0x6f, 0x6e,
	0x67, 0x2f, 0x62, 0x63, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_provenance_metadata_proto_rawDescOnce sync.Once
	file_provenance_metadata_proto_rawDescData = file_provenance_metadata_proto_rawDesc
)

func file_provenance_metadata_proto_rawDescGZIP() []byte {
	file_provenance_metadata_proto_rawDescOnce.Do(func() {
		file_provenance_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_provenance_metadata_proto_rawDescData)
	})
	return file_provenance_metadata_proto_rawDescData
}

var file_provenance_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_provenance_metadata_proto_goTypes = []interface{}{
	(*ProvenanceMetaData)(nil),     // 0: provenance_metadata_proto.ProvenanceMetaData
	(*ProvenanceMetaDataList)(nil), // 1: provenance_metadata_proto.ProvenanceMetaDataList
}
var file_provenance_metadata_proto_depIdxs = []int32{
	0, // 0: provenance_metadata_proto.ProvenanceMetaDataList.metadata:type_name -> provenance_metadata_proto.ProvenanceMetaData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_provenance_metadata_proto_init() }
func file_provenance_metadata_proto_init() {
	if File_provenance_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_provenance_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvenanceMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provenance_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvenanceMetaDataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_provenance_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provenance_metadata_proto_goTypes,
		DependencyIndexes: file_provenance_metadata_proto_depIdxs,
		MessageInfos:      file_provenance_metadata_proto_msgTypes,
	}.Build()
	File_provenance_metadata_proto = out.File
	file_provenance_metadata_proto_rawDesc = nil
	file_provenance_metadata_proto_goTypes = nil
	file_provenance_metadata_proto_depIdxs = nil
}
