// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: owner_team.proto

package owner_team_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OwnerTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED: Name of the build target
	TargetName *string `protobuf:"bytes,1,opt,name=target_name,json=targetName" json:"target_name,omitempty"`
	// REQUIRED: Code location of the target.
	// To be used to support legacy/backup systems that use OWNERS file and is
	// also required for our dashboard to support per code location basis UI
	Path *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// REQUIRED: Team ID of the team that owns this target.
	TrendyTeamId *string `protobuf:"bytes,3,opt,name=trendy_team_id,json=trendyTeamId" json:"trendy_team_id,omitempty"`
}

func (x *OwnerTeam) Reset() {
	*x = OwnerTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_owner_team_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerTeam) ProtoMessage() {}

func (x *OwnerTeam) ProtoReflect() protoreflect.Message {
	mi := &file_owner_team_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerTeam.ProtoReflect.Descriptor instead.
func (*OwnerTeam) Descriptor() ([]byte, []int) {
	return file_owner_team_proto_rawDescGZIP(), []int{0}
}

func (x *OwnerTeam) GetTargetName() string {
	if x != nil && x.TargetName != nil {
		return *x.TargetName
	}
	return ""
}

func (x *OwnerTeam) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *OwnerTeam) GetTrendyTeamId() string {
	if x != nil && x.TrendyTeamId != nil {
		return *x.TrendyTeamId
	}
	return ""
}

type AllOwnerTeams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerTeams []*OwnerTeam `protobuf:"bytes,1,rep,name=owner_teams,json=ownerTeams" json:"owner_teams,omitempty"`
}

func (x *AllOwnerTeams) Reset() {
	*x = AllOwnerTeams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_owner_team_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllOwnerTeams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOwnerTeams) ProtoMessage() {}

func (x *AllOwnerTeams) ProtoReflect() protoreflect.Message {
	mi := &file_owner_team_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOwnerTeams.ProtoReflect.Descriptor instead.
func (*AllOwnerTeams) Descriptor() ([]byte, []int) {
	return file_owner_team_proto_rawDescGZIP(), []int{1}
}

func (x *AllOwnerTeams) GetOwnerTeams() []*OwnerTeam {
	if x != nil {
		return x.OwnerTeams
	}
	return nil
}

var File_owner_team_proto protoreflect.FileDescriptor

var file_owner_team_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x61,
	0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x79,
	0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x72, 0x65, 0x6e, 0x64, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x3c, 0x0a,
	0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x42, 0x28, 0x5a, 0x26, 0x61,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x73, 0x6f, 0x6f, 0x6e, 0x67, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_owner_team_proto_rawDescOnce sync.Once
	file_owner_team_proto_rawDescData = file_owner_team_proto_rawDesc
)

func file_owner_team_proto_rawDescGZIP() []byte {
	file_owner_team_proto_rawDescOnce.Do(func() {
		file_owner_team_proto_rawDescData = protoimpl.X.CompressGZIP(file_owner_team_proto_rawDescData)
	})
	return file_owner_team_proto_rawDescData
}

var file_owner_team_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_owner_team_proto_goTypes = []interface{}{
	(*OwnerTeam)(nil),     // 0: owner_team_proto.OwnerTeam
	(*AllOwnerTeams)(nil), // 1: owner_team_proto.AllOwnerTeams
}
var file_owner_team_proto_depIdxs = []int32{
	0, // 0: owner_team_proto.AllOwnerTeams.owner_teams:type_name -> owner_team_proto.OwnerTeam
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_owner_team_proto_init() }
func file_owner_team_proto_init() {
	if File_owner_team_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_owner_team_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_owner_team_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllOwnerTeams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_owner_team_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_owner_team_proto_goTypes,
		DependencyIndexes: file_owner_team_proto_depIdxs,
		MessageInfos:      file_owner_team_proto_msgTypes,
	}.Build()
	File_owner_team_proto = out.File
	file_owner_team_proto_rawDesc = nil
	file_owner_team_proto_goTypes = nil
	file_owner_team_proto_depIdxs = nil
}
