// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: code_metadata.proto

package code_metadata_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AndroidCodeMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of all test targets and their metadata.
	TestTargetMetadataList []*AndroidCodeMetadata_TestTargetMetadata `protobuf:"bytes,1,rep,name=test_target_metadata_list,json=testTargetMetadataList" json:"test_target_metadata_list,omitempty"`
}

func (x *AndroidCodeMetadata) Reset() {
	*x = AndroidCodeMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndroidCodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidCodeMetadata) ProtoMessage() {}

func (x *AndroidCodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_code_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidCodeMetadata.ProtoReflect.Descriptor instead.
func (*AndroidCodeMetadata) Descriptor() ([]byte, []int) {
	return file_code_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *AndroidCodeMetadata) GetTestTargetMetadataList() []*AndroidCodeMetadata_TestTargetMetadata {
	if x != nil {
		return x.TestTargetMetadataList
	}
	return nil
}

type AndroidCodeMetadata_TestTargetMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetName   *string `protobuf:"bytes,1,opt,name=target_name,json=targetName" json:"target_name,omitempty"`
	Path         *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	TrendyTeamId *string `protobuf:"bytes,3,opt,name=trendy_team_id,json=trendyTeamId" json:"trendy_team_id,omitempty"`
}

func (x *AndroidCodeMetadata_TestTargetMetadata) Reset() {
	*x = AndroidCodeMetadata_TestTargetMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndroidCodeMetadata_TestTargetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidCodeMetadata_TestTargetMetadata) ProtoMessage() {}

func (x *AndroidCodeMetadata_TestTargetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_code_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidCodeMetadata_TestTargetMetadata.ProtoReflect.Descriptor instead.
func (*AndroidCodeMetadata_TestTargetMetadata) Descriptor() ([]byte, []int) {
	return file_code_metadata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AndroidCodeMetadata_TestTargetMetadata) GetTargetName() string {
	if x != nil && x.TargetName != nil {
		return *x.TargetName
	}
	return ""
}

func (x *AndroidCodeMetadata_TestTargetMetadata) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *AndroidCodeMetadata_TestTargetMetadata) GetTrendyTeamId() string {
	if x != nil && x.TrendyTeamId != nil {
		return *x.TrendyTeamId
	}
	return ""
}

var File_code_metadata_proto protoreflect.FileDescriptor

var file_code_metadata_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe, 0x01, 0x0a, 0x13, 0x41,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x76, 0x0a, 0x19, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x16, 0x74, 0x65, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x6f, 0x0a, 0x12, 0x54, 0x65,
	0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x79, 0x5f,
	0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x72, 0x65, 0x6e, 0x64, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x42, 0x2b, 0x5a, 0x29, 0x61,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x73, 0x6f, 0x6f, 0x6e, 0x67, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_code_metadata_proto_rawDescOnce sync.Once
	file_code_metadata_proto_rawDescData = file_code_metadata_proto_rawDesc
)

func file_code_metadata_proto_rawDescGZIP() []byte {
	file_code_metadata_proto_rawDescOnce.Do(func() {
		file_code_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_code_metadata_proto_rawDescData)
	})
	return file_code_metadata_proto_rawDescData
}

var file_code_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_metadata_proto_goTypes = []interface{}{
	(*AndroidCodeMetadata)(nil),                    // 0: code_metadata_proto.AndroidCodeMetadata
	(*AndroidCodeMetadata_TestTargetMetadata)(nil), // 1: code_metadata_proto.AndroidCodeMetadata.TestTargetMetadata
}
var file_code_metadata_proto_depIdxs = []int32{
	1, // 0: code_metadata_proto.AndroidCodeMetadata.test_target_metadata_list:type_name -> code_metadata_proto.AndroidCodeMetadata.TestTargetMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_code_metadata_proto_init() }
func file_code_metadata_proto_init() {
	if File_code_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndroidCodeMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndroidCodeMetadata_TestTargetMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_metadata_proto_goTypes,
		DependencyIndexes: file_code_metadata_proto_depIdxs,
		MessageInfos:      file_code_metadata_proto_msgTypes,
	}.Build()
	File_code_metadata_proto = out.File
	file_code_metadata_proto_rawDesc = nil
	file_code_metadata_proto_goTypes = nil
	file_code_metadata_proto_depIdxs = nil
}
