// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build_status.proto

package build_status_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildStatus_RESULT int32

const (
	BuildStatus_PASSED BuildStatus_RESULT = 0
	BuildStatus_FAILED BuildStatus_RESULT = 1
)

var BuildStatus_RESULT_name = map[int32]string{
	0: "PASSED",
	1: "FAILED",
}

var BuildStatus_RESULT_value = map[string]int32{
	"PASSED": 0,
	"FAILED": 1,
}

func (x BuildStatus_RESULT) Enum() *BuildStatus_RESULT {
	p := new(BuildStatus_RESULT)
	*p = x
	return p
}

func (x BuildStatus_RESULT) String() string {
	return proto.EnumName(BuildStatus_RESULT_name, int32(x))
}

func (x *BuildStatus_RESULT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BuildStatus_RESULT_value, data, "BuildStatus_RESULT")
	if err != nil {
		return err
	}
	*x = BuildStatus_RESULT(value)
	return nil
}

func (BuildStatus_RESULT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cfe68dd955928b30, []int{0, 0}
}

type BuildStatus struct {
	// The overall build result.
	Result *BuildStatus_RESULT `protobuf:"varint,1,opt,name=result,enum=build_status.BuildStatus_RESULT" json:"result,omitempty"`
	// List of error messages of the overall build.
	ErrorMessages []string `protobuf:"bytes,2,rep,name=error_messages,json=errorMessages" json:"error_messages,omitempty"`
	// List of build action errors.
	ActionErrors         []*BuildActionError `protobuf:"bytes,3,rep,name=action_errors,json=actionErrors" json:"action_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BuildStatus) Reset()         { *m = BuildStatus{} }
func (m *BuildStatus) String() string { return proto.CompactTextString(m) }
func (*BuildStatus) ProtoMessage()    {}
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe68dd955928b30, []int{0}
}

func (m *BuildStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildStatus.Unmarshal(m, b)
}
func (m *BuildStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildStatus.Marshal(b, m, deterministic)
}
func (m *BuildStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildStatus.Merge(m, src)
}
func (m *BuildStatus) XXX_Size() int {
	return xxx_messageInfo_BuildStatus.Size(m)
}
func (m *BuildStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BuildStatus proto.InternalMessageInfo

func (m *BuildStatus) GetResult() BuildStatus_RESULT {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return BuildStatus_PASSED
}

func (m *BuildStatus) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

func (m *BuildStatus) GetActionErrors() []*BuildActionError {
	if m != nil {
		return m.ActionErrors
	}
	return nil
}

type BuildActionError struct {
	// Description of the error.
	Description *string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// The build command that raised the error.
	Command *string `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	// Any additional output from the executed command.
	Output *string `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	// The error string that failed the build.
	Error                *string  `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildActionError) Reset()         { *m = BuildActionError{} }
func (m *BuildActionError) String() string { return proto.CompactTextString(m) }
func (*BuildActionError) ProtoMessage()    {}
func (*BuildActionError) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe68dd955928b30, []int{1}
}

func (m *BuildActionError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildActionError.Unmarshal(m, b)
}
func (m *BuildActionError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildActionError.Marshal(b, m, deterministic)
}
func (m *BuildActionError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildActionError.Merge(m, src)
}
func (m *BuildActionError) XXX_Size() int {
	return xxx_messageInfo_BuildActionError.Size(m)
}
func (m *BuildActionError) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildActionError.DiscardUnknown(m)
}

var xxx_messageInfo_BuildActionError proto.InternalMessageInfo

func (m *BuildActionError) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *BuildActionError) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *BuildActionError) GetOutput() string {
	if m != nil && m.Output != nil {
		return *m.Output
	}
	return ""
}

func (m *BuildActionError) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("build_status.BuildStatus_RESULT", BuildStatus_RESULT_name, BuildStatus_RESULT_value)
	proto.RegisterType((*BuildStatus)(nil), "build_status.BuildStatus")
	proto.RegisterType((*BuildActionError)(nil), "build_status.BuildActionError")
}

func init() { proto.RegisterFile("build_status.proto", fileDescriptor_cfe68dd955928b30) }

var fileDescriptor_cfe68dd955928b30 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0xa3, 0x91, 0x4e, 0x3f, 0x08, 0x83, 0x94, 0x3d, 0xc9, 0x12, 0x10, 0x72, 0xca,
	0xa1, 0x27, 0xaf, 0xa9, 0x8d, 0x28, 0x54, 0x90, 0x44, 0x2f, 0x5e, 0xc2, 0x9a, 0x2c, 0x12, 0x68,
	0xba, 0x61, 0x3f, 0x6e, 0xfe, 0x4d, 0xff, 0x8f, 0x64, 0x1a, 0x31, 0x15, 0x6f, 0xf3, 0x3c, 0xf3,
	0x32, 0xc3, 0x0c, 0xe0, 0xbb, 0x6b, 0xf6, 0x75, 0x69, 0xac, 0xb0, 0xce, 0x24, 0x9d, 0x56, 0x56,
	0xe1, 0x7c, 0xec, 0xa2, 0x2f, 0x0f, 0x66, 0x9b, 0x5e, 0x14, 0xc4, 0x78, 0x0b, 0x81, 0x96, 0xc6,
	0xed, 0x2d, 0xf3, 0xb8, 0x17, 0x2f, 0xd7, 0x3c, 0x39, 0x19, 0x31, 0x8a, 0x26, 0x79, 0x56, 0xbc,
	0xee, 0x5e, 0xf2, 0x21, 0x8f, 0x37, 0xb0, 0x94, 0x5a, 0x2b, 0x5d, 0xb6, 0xd2, 0x18, 0xf1, 0x21,
	0x0d, 0x9b, 0x70, 0x3f, 0x9e, 0xe6, 0x0b, 0xb2, 0x4f, 0x83, 0xc4, 0x3b, 0x58, 0x88, 0xca, 0x36,
	0xea, 0x50, 0x92, 0x37, 0xcc, 0xe7, 0x7e, 0x3c, 0x5b, 0x5f, 0xff, 0xb3, 0x27, 0xa5, 0x5c, 0xd6,
	0xc7, 0xf2, 0xb9, 0xf8, 0x05, 0x13, 0x71, 0x08, 0x8e, 0xdb, 0x11, 0x20, 0x78, 0x4e, 0x8b, 0x22,
	0xdb, 0x86, 0x67, 0x7d, 0x7d, 0x9f, 0x3e, 0xee, 0xb2, 0x6d, 0xe8, 0x45, 0x9f, 0x10, 0xfe, 0x9d,
	0x81, 0x1c, 0x66, 0xb5, 0x34, 0x95, 0x6e, 0xba, 0xde, 0xd1, 0x81, 0xd3, 0x7c, 0xac, 0x90, 0xc1,
	0x65, 0xa5, 0xda, 0x56, 0x1c, 0x6a, 0x36, 0xa1, 0xee, 0x0f, 0xe2, 0x0a, 0x02, 0xe5, 0x6c, 0xe7,
	0x2c, 0xf3, 0xa9, 0x31, 0x10, 0x5e, 0xc1, 0x05, 0xdd, 0xc1, 0xce, 0x49, 0x1f, 0x61, 0xb3, 0x7a,
	0xf0, 0xdf, 0x4e, 0x7e, 0x5f, 0xd2, 0xef, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x02, 0x9c, 0xe7,
	0x43, 0x90, 0x01, 0x00, 0x00,
}
